import { apiOk, apiError } from "@/lib/api-response";
import { saveCard } from "@/lib/card-crawler";
import type { CardData } from "@/lib/card-crawler";

const SAMPLE_CARDS: CardData[] = [
  {
    gorilla_id: 9001,
    name: "신한 Deep Dream 카드",
    company: "신한카드",
    annual_fee: "국내전용 10,000원 / 해외겸용 20,000원",
    min_spending: "전월 30만원",
    brand: "VISA / Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "편의점·마트", summary: "GS25·CU·세븐일레븐·이마트24 5% 할인 (월 2,000원 한도)" },
      { category: "카페", summary: "스타벅스·투썸플레이스·이디야 5% 할인 (월 2,000원 한도)" },
      { category: "배달", summary: "배달의민족·쿠팡이츠·요기요 5% 할인 (월 2,000원 한도)" },
      { category: "통신", summary: "SK텔레콤·KT·LG U+ 통신요금 10% 할인" },
      { category: "교통", summary: "대중교통 10% 할인 (월 5,000원 한도)" },
    ],
  },
  {
    gorilla_id: 9002,
    name: "삼성 taptap O 카드",
    company: "삼성카드",
    annual_fee: "국내전용 15,000원 / 해외겸용 20,000원",
    min_spending: "전월 40만원",
    brand: "VISA / Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "온라인쇼핑", summary: "쿠팡·네이버쇼핑·G마켓 10% 할인 (월 5,000원 한도)" },
      { category: "주유", summary: "전국 주유소 리터당 80원 할인" },
      { category: "통신", summary: "이동통신 요금 10% 할인" },
      { category: "스트리밍", summary: "넷플릭스·유튜브 프리미엄 10% 할인" },
    ],
  },
  {
    gorilla_id: 9003,
    name: "현대카드 M booster 플래티넘",
    company: "현대카드",
    annual_fee: "30,000원",
    min_spending: "전월 40만원",
    brand: "Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "M포인트", summary: "모든 가맹점 최대 5% M포인트 적립" },
      { category: "백화점", summary: "현대백화점·아이파크몰·현대프리미엄아울렛 5% 적립" },
      { category: "주유", summary: "현대오일뱅크 리터당 100원 할인" },
      { category: "공항라운지", summary: "국내외 공항 라운지 연 2회 무료 이용" },
    ],
  },
  {
    gorilla_id: 9004,
    name: "KB국민 My WE 카드",
    company: "KB국민카드",
    annual_fee: "없음",
    min_spending: "전월 30만원",
    brand: "VISA / Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "캐시백", summary: "1만원 이상 이용 시 월 2,000원 캐시백" },
      { category: "카페", summary: "스타벅스·커피빈·CU 5% 할인" },
      { category: "OTT", summary: "넷플릭스·왓챠·티빙 10% 할인 (월 2,000원 한도)" },
      { category: "교통", summary: "대중교통 10% 할인 (월 3,000원 한도)" },
    ],
  },
  {
    gorilla_id: 9005,
    name: "롯데 LOCA 365",
    company: "롯데카드",
    annual_fee: "없음",
    min_spending: "전월 30만원",
    brand: "VISA",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "대형마트", summary: "롯데마트·롯데슈퍼 5% 할인 (월 3,000원 한도)" },
      { category: "배달", summary: "배달의민족 5% 할인 (월 2,000원 한도)" },
      { category: "외식", summary: "롯데리아·엔제리너스·TGI 5% 할인" },
      { category: "놀이공원", summary: "롯데월드·롯데워터파크 3,000원 할인" },
    ],
  },
  {
    gorilla_id: 9006,
    name: "우리 카드의정석 EVERYDAY",
    company: "우리카드",
    annual_fee: "4,000원",
    min_spending: "전월 30만원",
    brand: "VISA",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "전 가맹점", summary: "전월 30만원 이상 시 0.7% 청구 할인" },
      { category: "대중교통", summary: "버스·지하철 5% 할인 (월 2,000원 한도)" },
      { category: "편의점", summary: "GS25·CU·세븐일레븐 5% 할인 (월 1,000원 한도)" },
    ],
  },
  {
    gorilla_id: 9007,
    name: "하나 1Q Pay 카드",
    company: "하나카드",
    annual_fee: "없음",
    min_spending: "전월 30만원",
    brand: "Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "교통", summary: "대중교통 무제한 10% 할인" },
      { category: "간편결제", summary: "네이버페이·카카오페이·SSG페이 5% 할인" },
      { category: "공항라운지", summary: "국내외 공항 라운지 연 2회 무료" },
      { category: "통신", summary: "이동통신 5% 할인 (월 2,000원 한도)" },
    ],
  },
  {
    gorilla_id: 9008,
    name: "NH올원 e카드",
    company: "NH농협카드",
    annual_fee: "없음",
    min_spending: "전월 20만원",
    brand: "Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "온라인쇼핑", summary: "쿠팡·네이버쇼핑 3% 캐시백 (월 5,000원 한도)" },
      { category: "스트리밍", summary: "멜론·지니뮤직 20% 할인" },
      { category: "편의점", summary: "GS25·CU 5% 할인 (월 1,500원 한도)" },
      { category: "금융", summary: "NH농협ATM 타행이체 수수료 면제" },
    ],
  },
  {
    gorilla_id: 9009,
    name: "카카오뱅크 체크카드",
    company: "카카오뱅크",
    annual_fee: "없음",
    min_spending: "없음",
    brand: "Master",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "해외결제", summary: "해외 결제 수수료 무료 (전 가맹점)" },
      { category: "쇼핑", summary: "카카오커머스 2% 캐시백" },
      { category: "편의점", summary: "GS25 5% 할인 (월 2,000원 한도)" },
      { category: "카페", summary: "스타벅스·투썸 3% 할인" },
    ],
  },
  {
    gorilla_id: 9010,
    name: "토스 머니 체크카드",
    company: "토스뱅크",
    annual_fee: "없음",
    min_spending: "없음",
    brand: "VISA",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "전 가맹점", summary: "전 가맹점 0.2% 캐시백 (한도 없음)" },
      { category: "교통", summary: "지하철·버스 5% 캐시백 (월 2,000원 한도)" },
      { category: "배달", summary: "배달의민족·쿠팡이츠 2% 캐시백" },
      { category: "해외", summary: "해외 이용 수수료 면제" },
    ],
  },
  {
    gorilla_id: 9011,
    name: "신한 SOL Pay 카드",
    company: "신한카드",
    annual_fee: "없음",
    min_spending: "전월 30만원",
    brand: "VISA",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "SOL Pay", summary: "신한 SOL Pay 결제 시 5% 청구할인 (월 2회)" },
      { category: "편의점", summary: "CU·GS25 5% 할인 (월 1,500원 한도)" },
      { category: "카페", summary: "투썸플레이스·파리바게뜨 5% 할인" },
      { category: "배달", summary: "배달의민족 3% 할인" },
    ],
  },
  {
    gorilla_id: 9012,
    name: "삼성 iD DRIVE 카드",
    company: "삼성카드",
    annual_fee: "10,000원",
    min_spending: "전월 30만원",
    brand: "iD",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "주유", summary: "전국 주유소 리터당 70원 할인 (월 6,000원 한도)" },
      { category: "하이패스", summary: "하이패스 통행료 40% 할인 (월 3,000원 한도)" },
      { category: "자동차 정비", summary: "자동차 정비·세차 5% 할인" },
      { category: "주차", summary: "공용주차장 5% 할인" },
    ],
  },
  {
    gorilla_id: 9013,
    name: "현대 제로 에디션2",
    company: "현대카드",
    annual_fee: "50,000원",
    min_spending: "전월 50만원",
    brand: "Amex",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "무이자할부", summary: "전 가맹점 2~6개월 무이자할부 무제한" },
      { category: "백화점", summary: "신세계·현대·롯데백화점 5% 할인" },
      { category: "포인트", summary: "모든 결제 0.7% M포인트 적립" },
      { category: "라운지", summary: "국내외 공항 라운지 연 4회 무료" },
    ],
  },
  {
    gorilla_id: 9014,
    name: "신한 Fan 카드",
    company: "신한카드",
    annual_fee: "없음",
    min_spending: "전월 20만원",
    brand: "VISA",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "교육", summary: "교육비 (학원·어학원·온라인강의) 2% 캐시백" },
      { category: "온라인쇼핑", summary: "G마켓·옥션·11번가 5% 할인 (월 3,000원 한도)" },
      { category: "여가", summary: "영화관·놀이공원·스포츠 5% 할인 (월 3,000원 한도)" },
    ],
  },
  {
    gorilla_id: 9015,
    name: "KB국민 탄탄대로 ALL카드",
    company: "KB국민카드",
    annual_fee: "없음",
    min_spending: "전월 30만원",
    brand: "Master / UnionPay",
    image_url: "",
    crawled_at: new Date().toISOString(),
    benefits: [
      { category: "OK캐쉬백", summary: "OK캐쉬백 가맹점 이용 시 0.5% 추가 적립" },
      { category: "교통", summary: "대중교통 10% 할인 (월 5,000원 한도)" },
      { category: "통신", summary: "SK텔레콤·KT·LG U+ 5% 할인 (월 2,000원 한도)" },
      { category: "마트", summary: "이마트·홈플러스·롯데마트 3% 캐시백" },
    ],
  },
];

export async function POST() {
  try {
    let count = 0;
    for (const card of SAMPLE_CARDS) {
      await saveCard(card);
      count++;
    }
    return apiOk({ count }, { message: `샘플 카드 ${count}건 추가 완료` });
  } catch (err) {
    return apiError({
      status: 500,
      code: "SEED_ERROR",
      message: "샘플 데이터 추가 실패",
      details: err instanceof Error ? err.message : String(err),
    });
  }
}
