export interface GosaEntry {
  word: string;
  hanja: string;
  meaning: string;
  english: string;
  tags?: string[];
}

export interface SodamEntry {
  sodam: string;
  meaning: string;
  english: string;
  tags?: string[];
}

export const GOSA_DATA: GosaEntry[] = [
  { word: "일석이조", hanja: "一石二鳥", meaning: "돌 하나로 새 두 마리를 잡는다는 뜻으로, 하나의 행동으로 두 가지 이익을 얻음", english: "Kill two birds with one stone", tags: ["지혜", "효율"] },
  { word: "과유불급", hanja: "過猶不及", meaning: "지나친 것은 부족함만 못하다. 적당한 것이 최선임", english: "Too much is as bad as too little", tags: ["절제"] },
  { word: "청출어람", hanja: "靑出於藍", meaning: "쪽에서 나온 파란색이 쪽빛보다 더 파람 → 제자가 스승보다 뛰어남", english: "The student surpasses the teacher", tags: ["성장", "배움"] },
  { word: "살신성인", hanja: "殺身成仁", meaning: "자신의 몸을 희생하여 인(仁)을 이룸. 대의를 위해 자신을 바침", english: "Sacrifice oneself for righteousness", tags: ["희생", "용기"] },
  { word: "온고지신", hanja: "溫故知新", meaning: "옛것을 익히고 그것으로 새것을 앎. 역사와 전통에서 배움", english: "Review the old and learn the new", tags: ["배움", "지혜"] },
  { word: "오십보백보", hanja: "五十步百步", meaning: "오십 보 도망간 자가 백 보 도망간 자를 비웃음 → 본질적 차이가 없음", english: "Six of one, half a dozen of the other", tags: ["비교"] },
  { word: "유유상종", hanja: "類類相從", meaning: "같은 무리끼리 서로 어울림. 성격·처지가 비슷한 사람들이 모임", english: "Birds of a feather flock together", tags: ["인간관계"] },
  { word: "동고동락", hanja: "同苦同樂", meaning: "괴로움과 즐거움을 함께 나눔", english: "Share joys and sorrows together", tags: ["인간관계", "우정"] },
  { word: "사면초가", hanja: "四面楚歌", meaning: "사방이 적의 노래 소리로 가득함 → 고립무원의 위험 상황", english: "Surrounded by enemies on all sides", tags: ["위기"] },
  { word: "막상막하", hanja: "莫上莫下", meaning: "위도 아래도 없다는 뜻으로, 서로 우열을 가리기 어려울 만큼 비슷함", english: "Neck and neck; evenly matched", tags: ["비교"] },
  { word: "전화위복", hanja: "轉禍爲福", meaning: "재화(災禍)가 바뀌어 복이 됨. 나쁜 일이 결국 좋은 결과로 이어짐", english: "A blessing in disguise", tags: ["긍정", "희망"] },
  { word: "호사다마", hanja: "好事多魔", meaning: "좋은 일에는 방해가 많음. 잘 될 때일수록 조심해야 함", english: "Good things often come with obstacles", tags: ["조심"] },
  { word: "동병상련", hanja: "同病相憐", meaning: "같은 병을 앓는 사람끼리 서로 불쌍히 여김. 같은 처지에서 생기는 공감", english: "Misery loves company", tags: ["공감", "인간관계"] },
  { word: "이심전심", hanja: "以心傳心", meaning: "마음에서 마음으로 전해짐. 말하지 않아도 서로 통함", english: "Heart to heart; unspoken understanding", tags: ["소통", "우정"] },
  { word: "백문불여일견", hanja: "百聞不如一見", meaning: "백 번 듣는 것이 한 번 보는 것만 못함. 직접 경험이 중요함", english: "Seeing is believing", tags: ["경험", "지혜"] },
  { word: "대기만성", hanja: "大器晩成", meaning: "큰 그릇은 늦게 이루어짐 → 크게 될 사람은 늦게 성공함", english: "Great talents mature slowly", tags: ["성장", "인내"] },
  { word: "괄목상대", hanja: "刮目相對", meaning: "눈을 비비고 다시 보다 → 상대의 발전이 놀라울 정도임", english: "Look at someone with fresh eyes; admire remarkable progress", tags: ["성장", "발전"] },
  { word: "표리부동", hanja: "表裏不同", meaning: "겉과 속이 다름. 말과 행동이 일치하지 않음", english: "Two-faced; saying one thing and doing another", tags: ["인성"] },
  { word: "군계일학", hanja: "群鷄一鶴", meaning: "닭 무리 중의 학 한 마리 → 여러 사람 중에 특별히 뛰어난 사람", english: "A crane among chickens; standing out from the crowd", tags: ["탁월함"] },
  { word: "금상첨화", hanja: "錦上添花", meaning: "비단 위에 꽃을 더함 → 좋은 일에 더 좋은 일이 겹침", english: "The icing on the cake", tags: ["행운"] },
  { word: "설상가상", hanja: "雪上加霜", meaning: "눈 위에 서리가 내림 → 불행이 잇따라 겹침", english: "Adding insult to injury; from bad to worse", tags: ["불운", "위기"] },
  { word: "청천벽력", hanja: "靑天霹靂", meaning: "맑은 하늘에 날벼락 → 뜻밖의 큰 충격이나 변고", english: "A bolt from the blue; unexpected shock", tags: ["충격"] },
  { word: "동문서답", hanja: "東問西答", meaning: "동쪽을 물으니 서쪽을 답함 → 질문의 요점을 빗나간 엉뚱한 대답", english: "Answering a question with an irrelevant answer", tags: ["소통"] },
  { word: "임기응변", hanja: "臨機應變", meaning: "때와 형편에 따라 적절하게 대처함", english: "Adapting to the situation; quick thinking", tags: ["지혜", "대처"] },
  { word: "칠전팔기", hanja: "七顚八起", meaning: "일곱 번 넘어지고 여덟 번 일어남 → 어떤 실패에도 굴하지 않는 불굴의 의지", english: "Fall seven times, stand up eight; resilience", tags: ["용기", "인내", "노력"] },
  { word: "사필귀정", hanja: "事必歸正", meaning: "모든 일은 반드시 바른 데로 돌아감. 결국 옳고 그름이 밝혀짐", english: "Justice will prevail in the end", tags: ["정의"] },
  { word: "고진감래", hanja: "苦盡甘來", meaning: "쓴 것이 다하면 단 것이 옴 → 고생 끝에 낙이 옴", english: "After hardship comes happiness", tags: ["희망", "인내"] },
  { word: "자업자득", hanja: "自業自得", meaning: "자신이 저지른 일의 결과를 자신이 받음. 뿌린 대로 거둠", english: "You reap what you sow", tags: ["인과"] },
  { word: "학수고대", hanja: "鶴首苦待", meaning: "학처럼 목을 길게 빼고 몹시 기다림", english: "Eagerly waiting with outstretched neck", tags: ["기다림"] },
  { word: "일취월장", hanja: "日就月將", meaning: "날로 나아가고 달로 발전함 → 꾸준히 성장함", english: "Making progress day by day and month by month", tags: ["성장", "노력"] },
  { word: "주마간산", hanja: "走馬看山", meaning: "말을 타고 달리면서 산을 봄 → 자세히 살피지 않고 대충 훑어봄", english: "A cursory glance; viewing while speeding past", tags: ["태도"] },
  { word: "수수방관", hanja: "袖手傍觀", meaning: "팔짱을 낀 채 곁에서 구경만 함 → 관여하지 않고 내버려 둠", english: "Standing by with folded arms; turning a blind eye", tags: ["태도"] },
  { word: "배은망덕", hanja: "背恩忘德", meaning: "받은 은혜를 저버리고 도리어 배반함", english: "Biting the hand that feeds you; ingratitude", tags: ["인성"] },
  { word: "구사일생", hanja: "九死一生", meaning: "아홉 번 죽을 고비에서 겨우 살아남 → 기적적으로 살아남", english: "A narrow escape from death", tags: ["위기", "용기"] },
  { word: "어불성설", hanja: "語不成說", meaning: "말이 사리에 맞지 않아 이치가 없음", english: "That doesn't make sense; illogical argument", tags: ["소통"] },
  { word: "역지사지", hanja: "易地思之", meaning: "처지를 바꾸어 생각해 봄 → 상대방의 입장에서 헤아림", english: "Put yourself in another's shoes", tags: ["공감", "이해"] },
  { word: "오비이락", hanja: "烏飛梨落", meaning: "까마귀 날자 배 떨어진다 → 공교롭게 두 일이 같은 때에 일어남", english: "Guilty by coincidence; two unrelated things happening simultaneously", tags: ["오해"] },
  { word: "좌불안석", hanja: "坐不安席", meaning: "앉아 있어도 자리가 편하지 않음 → 불안하여 안절부절못함", english: "Unable to sit still; feeling uneasy and restless", tags: ["불안"] },
  { word: "조삼모사", hanja: "朝三暮四", meaning: "아침에 세 개, 저녁에 네 개 → 간사한 꾀로 남을 속임. 결국 같은 것을 당장만 다른 것처럼 속임", english: "Short-term thinking; being fooled by superficial differences", tags: ["기만"] },
  { word: "인과응보", hanja: "因果應報", meaning: "원인에 따라 결과가 응함. 선한 일에는 선한 결과, 악한 일에는 악한 결과", english: "Karma; what goes around comes around", tags: ["인과", "정의"] },
  { word: "독불장군", hanja: "獨不將軍", meaning: "혼자서는 장군이 될 수 없다 → 독단적이고 남과 어울리지 못하는 사람", english: "No man is an island; can't succeed alone", tags: ["협력", "인간관계"] },
  { word: "점입가경", hanja: "漸入佳境", meaning: "점점 더 좋은 경지로 들어감. 또는 일이 점점 더 재미있어지거나 어이없어짐", english: "Getting more and more interesting (or outrageous)", tags: ["변화"] },
  { word: "온화지신", hanja: "溫和之信", meaning: "온화하고 믿음직함. 부드러운 덕성을 갖춤", english: "Gentle and trustworthy character", tags: ["인성"] },
  { word: "화룡점정", hanja: "畵龍點睛", meaning: "용을 그린 뒤 눈동자를 찍음 → 가장 중요한 마지막 마무리로 완성도를 높임", english: "The finishing touch that brings something to life", tags: ["완성", "지혜"] },
  { word: "우공이산", hanja: "愚公移山", meaning: "우공이 산을 옮김 → 우직하게 꾸준히 노력하면 목표를 이룸", english: "Persistent effort can move mountains", tags: ["노력", "인내"] },
  { word: "견리사의", hanja: "見利思義", meaning: "이익을 보면 의로움을 생각함. 작은 이익보다 올바름을 먼저 생각함", english: "Think of righteousness before profit", tags: ["인성", "덕"] },
  { word: "지피지기", hanja: "知彼知己", meaning: "적을 알고 나를 앎 → 백 번 싸워도 지지 않음", english: "Know your enemy and know yourself", tags: ["전략", "지혜"] },
  { word: "십시일반", hanja: "十匙一飯", meaning: "열 사람이 한 숟가락씩 보태면 한 사람 밥이 됨 → 여럿이 조금씩 도우면 큰 힘이 됨", english: "Many a little makes a muckle; collective effort", tags: ["협력", "나눔"] },
  { word: "무릉도원", hanja: "武陵桃源", meaning: "이상적이고 아름다운 별세계 → 꿈 같은 이상향", english: "Utopia; an idyllic paradise", tags: ["이상"] },
  { word: "명실상부", hanja: "名實相符", meaning: "이름과 실제가 서로 들어맞음", english: "Living up to one's name; worthy of the title", tags: ["신뢰"] },
  // ── 추가 100선 ──
  { word: "수어지교", hanja: "水魚之交", meaning: "물과 물고기의 사귐처럼 매우 친밀하고 떼려야 뗄 수 없는 관계", english: "Inseparable friendship like fish and water", tags: ["우정", "인간관계"] },
  { word: "절치부심", hanja: "切齒腐心", meaning: "이를 갈고 마음에 새김. 매우 분하여 복수를 다짐", english: "Grinding teeth with resentment; burning desire for revenge", tags: ["분노", "의지"] },
  { word: "와신상담", hanja: "臥薪嘗膽", meaning: "장작 위에 자고 쓸개를 핥음. 목표 달성을 위해 온갖 고난을 참음", english: "Sleeping on brushwood and tasting gall; enduring hardship for revenge", tags: ["인내", "결의"] },
  { word: "견물생심", hanja: "見物生心", meaning: "물건을 보면 갖고 싶은 마음이 생김. 욕심은 눈앞의 것에서 비롯됨", english: "Seeing is coveting; desire arises from seeing", tags: ["욕심"] },
  { word: "교학상장", hanja: "敎學相長", meaning: "가르치고 배우면서 서로 성장함. 교사와 학생이 함께 발전함", english: "Teaching and learning promote each other's growth", tags: ["배움", "성장"] },
  { word: "형설지공", hanja: "螢雪之功", meaning: "반딧불과 눈빛으로 공부한 노력. 어려운 환경에서도 열심히 공부한 공로", english: "Studying by firefly light and snow; diligent study despite hardship", tags: ["노력", "배움"] },
  { word: "새옹지마", hanja: "塞翁之馬", meaning: "변방 노인의 말 이야기에서 유래. 인생의 길흉화복은 예측할 수 없음", english: "Fortune is unpredictable; every cloud has a silver lining", tags: ["인생", "희망"] },
  { word: "우후죽순", hanja: "雨後竹筍", meaning: "비 온 뒤의 죽순처럼 어떤 일이 한꺼번에 많이 생겨남", english: "Springing up like bamboo shoots after rain; rapid proliferation", tags: ["변화", "성장"] },
  { word: "좌고우면", hanja: "左顧右眄", meaning: "좌우를 두리번거림. 이것저것 재다가 결정을 못 하는 우유부단함", english: "Looking left and right; indecisive hesitation", tags: ["우유부단"] },
  { word: "이구동성", hanja: "異口同聲", meaning: "입은 달라도 소리는 같음. 여러 사람이 한목소리로 같은 말을 함", english: "Speaking with one voice; unanimous opinion", tags: ["소통", "일치"] },
  { word: "부화뇌동", hanja: "附和雷同", meaning: "우레처럼 남의 의견에 따름. 줏대 없이 남의 의견에 무조건 동조함", english: "Following blindly; jumping on the bandwagon", tags: ["태도"] },
  { word: "격세지감", hanja: "隔世之感", meaning: "세대가 달라진 느낌. 불과 얼마 전인데 세상이 몰라보게 달라진 느낌", english: "Feeling of a generation gap; the world has changed dramatically", tags: ["변화"] },
  { word: "일편단심", hanja: "一片丹心", meaning: "한 조각 붉은 마음. 변하지 않는 충성심이나 한결같은 사랑", english: "A heart of loyalty; single-hearted devotion", tags: ["충성", "사랑"] },
  { word: "어부지리", hanja: "漁父之利", meaning: "어부가 이익을 얻음. 두 세력이 다툴 때 제3자가 이득을 챙김", english: "Reaping the benefits while others fight; third-party gain", tags: ["지혜", "전략"] },
  { word: "중구난방", hanja: "衆口難防", meaning: "뭇 사람의 입을 막기 어려움. 여러 사람의 말이 뒤섞여 통제하기 어려움", english: "Hard to stop the mouths of the crowd; impossible to silence all voices", tags: ["소통"] },
  { word: "동분서주", hanja: "東奔西走", meaning: "동서로 바쁘게 뛰어다님. 이리저리 매우 바쁘게 돌아다님", english: "Running around in all directions; extremely busy", tags: ["노력", "활동"] },
  { word: "두문불출", hanja: "杜門不出", meaning: "문을 닫고 나오지 않음. 집에만 틀어박혀 외부 활동을 하지 않음", english: "Shutting the door and not going out; staying in seclusion", tags: ["은둔"] },
  { word: "오매불망", hanja: "寤寐不忘", meaning: "자나 깨나 잊지 못함. 무언가를 매우 그리워하거나 열망함", english: "Unable to forget even in sleep; longing day and night", tags: ["그리움"] },
  { word: "침소봉대", hanja: "針小棒大", meaning: "바늘만 한 작은 것을 막대기처럼 크게 말함. 사실을 과장함", english: "Making a mountain out of a molehill; exaggeration", tags: ["말", "과장"] },
  { word: "반면교사", hanja: "反面敎師", meaning: "반대편의 선생. 잘못된 것이나 실패에서 역으로 교훈을 얻음", english: "Learning from negative examples; a teacher by counterexample", tags: ["배움", "지혜"] },
  { word: "소탐대실", hanja: "小貪大失", meaning: "작은 것을 탐하다가 큰 것을 잃음. 욕심이 지나치면 더 큰 것을 놓침", english: "Penny-wise, pound-foolish; losing big while pursuing small gains", tags: ["욕심", "지혜"] },
  { word: "파죽지세", hanja: "破竹之勢", meaning: "대나무를 쪼개는 기세. 거침없이 적을 무너뜨리는 강한 기세", english: "Irresistible momentum; advancing like splitting bamboo", tags: ["기세", "용기"] },
  { word: "천고마비", hanja: "天高馬肥", meaning: "하늘은 높고 말은 살찐다. 가을의 맑고 풍요로운 계절을 나타냄", english: "High skies and plump horses; the abundance of autumn", tags: ["계절"] },
  { word: "수불석권", hanja: "手不釋卷", meaning: "손에서 책을 놓지 않음. 부지런히 공부하며 항상 책을 가까이함", english: "Never putting down a book; always studying diligently", tags: ["배움", "노력"] },
  { word: "만시지탄", hanja: "晩時之歎", meaning: "때가 너무 늦음을 한탄함. 이미 기회를 놓쳐 버린 것에 대한 아쉬움", english: "Lamenting that the right time has passed; too little too late", tags: ["후회"] },
  { word: "타산지석", hanja: "他山之石", meaning: "다른 산의 돌로 옥을 다듬음. 남의 단점이나 실수도 자신에게 교훈이 됨", english: "Using stones from other mountains; learning from others' faults", tags: ["배움", "지혜"] },
  { word: "허장성세", hanja: "虛張聲勢", meaning: "빈껍데기로 기세를 부림. 실속은 없으면서 겉으로만 기세를 과시함", english: "Bluffing; making an empty show of strength", tags: ["태도"] },
  { word: "인지상정", hanja: "人之常情", meaning: "사람이면 누구나 가지는 보통의 감정과 정서. 인간의 자연스러운 감정", english: "Human nature; the way of all flesh", tags: ["인간관계"] },
  { word: "언중유골", hanja: "言中有骨", meaning: "말 속에 뼈가 있음. 겉으로 농담처럼 들려도 진의가 담겨 있음", english: "Words with a hidden sting; more than meets the ear", tags: ["말", "소통"] },
  { word: "관포지교", hanja: "管鮑之交", meaning: "관중과 포숙아의 사귐. 이해관계를 넘어선 매우 깊고 변치 않는 우정", english: "Kuan and Pao's friendship; deep and selfless friendship", tags: ["우정"] },
  { word: "연목구어", hanja: "緣木求魚", meaning: "나무에 올라가 물고기를 구함. 방법이 잘못되어 결코 불가능한 일을 하려 함", english: "Climbing a tree to catch fish; seeking the impossible", tags: ["판단"] },
  { word: "대의명분", hanja: "大義名分", meaning: "큰 도의와 올바른 명분. 어떤 행동을 정당화하는 도덕적·논리적 근거", english: "Just cause and righteous justification; moral grounds for action", tags: ["정의", "도덕"] },
  { word: "화이부동", hanja: "和而不同", meaning: "조화롭게 지내되 무분별하게 따르지 않음. 독립성을 유지하며 협력함", english: "Harmonious but not conformist; agree to disagree", tags: ["협력", "독립"] },
  { word: "풍전등화", hanja: "風前燈火", meaning: "바람 앞의 등불처럼 매우 위태롭고 불안정한 처지", english: "A candle in the wind; extremely precarious situation", tags: ["위기"] },
  { word: "공전절후", hanja: "空前絶後", meaning: "전에도 없고 후에도 없음. 이전에도 이후에도 유례가 없는 일", english: "Unprecedented and unrepeatable; once in history", tags: ["탁월함"] },
  { word: "백년해로", hanja: "百年偕老", meaning: "백 년을 함께 늙음. 부부가 평생 화목하게 함께 삶", english: "Growing old together for a hundred years; lifelong marital bliss", tags: ["사랑", "가족"] },
  { word: "마이동풍", hanja: "馬耳東風", meaning: "말의 귀에 봄바람. 남의 말을 전혀 귀담아듣지 않고 흘려버림", english: "In one ear and out the other; ignoring advice", tags: ["태도", "소통"] },
  { word: "환골탈태", hanja: "換骨奪胎", meaning: "뼈를 바꾸고 태를 빼앗음. 사람이 완전히 새롭게 변하거나 작품이 완전히 탈바꿈함", english: "A complete transformation; reborn anew", tags: ["변화", "성장"] },
  { word: "팔방미인", hanja: "八方美人", meaning: "여덟 방향 모두 미인. 여러 방면에서 골고루 뛰어난 사람", english: "A jack of all trades; talented in many areas", tags: ["재능"] },
  { word: "백절불굴", hanja: "百折不屈", meaning: "백 번 꺾여도 굽히지 않음. 어떤 어려움에도 굴복하지 않는 강인한 의지", english: "Unbowed after a hundred setbacks; indomitable spirit", tags: ["의지", "용기"] },
  { word: "호연지기", hanja: "浩然之氣", meaning: "하늘과 땅 사이에 넘치는 크고 바른 기운. 도덕적으로 올바른 담대한 기상", english: "Boundless moral spirit; noble and upright character", tags: ["인성", "도덕"] },
  { word: "간담상조", hanja: "肝膽相照", meaning: "간과 쓸개를 서로 비춤. 속마음을 터놓고 나누는 깊은 우정", english: "Showing each other liver and gall; opening one's heart to a friend", tags: ["우정", "신뢰"] },
  { word: "명경지수", hanja: "明鏡止水", meaning: "맑은 거울과 고요한 물. 잡념 없이 평정하고 맑은 마음의 상태", english: "A clear mirror and still water; serene and untroubled mind", tags: ["마음", "평온"] },
  { word: "수구초심", hanja: "首丘初心", meaning: "여우가 죽을 때 고향 쪽으로 머리를 둠. 고향이나 근본을 그리워하는 마음", english: "Longing for one's homeland; the fox turns its head toward its lair", tags: ["고향", "그리움"] },
  { word: "천의무봉", hanja: "天衣無縫", meaning: "선녀의 옷에는 솔기가 없음. 완벽하여 조금도 흠이 없음", english: "Seamless as a celestial garment; flawless and perfect", tags: ["완벽"] },
  { word: "안분지족", hanja: "安分知足", meaning: "분수를 지키고 만족할 줄 앎. 욕심 없이 자기 처지에 만족하며 삶", english: "Content with one's lot; knowing when enough is enough", tags: ["만족", "절제"] },
  { word: "상전벽해", hanja: "桑田碧海", meaning: "뽕나무밭이 푸른 바다가 됨. 세상이 몰라보게 크게 바뀜", english: "Mulberry fields turn into blue sea; the world has changed completely", tags: ["변화"] },
  { word: "약육강식", hanja: "弱肉强食", meaning: "약한 것이 강한 것의 먹이가 됨. 강자만이 살아남는 힘의 논리", english: "The strong devour the weak; survival of the fittest", tags: ["경쟁"] },
  { word: "천재일우", hanja: "千載一遇", meaning: "천 년에 한 번 만날 기회. 평생 다시 오지 않을 매우 드문 기회", english: "A once-in-a-millennium chance; a rare opportunity", tags: ["기회"] },
  { word: "삼고초려", hanja: "三顧草廬", meaning: "제갈량의 초려를 세 번 찾아감. 훌륭한 인재를 얻기 위해 정성껏 예우함", english: "Visiting the thatched cottage three times; earnestly recruiting talent", tags: ["리더십", "인재"] },
  { word: "오월동주", hanja: "吳越同舟", meaning: "오나라와 월나라 사람이 같은 배를 탐. 원수지간도 공동의 위기 앞에서 협력함", english: "Enemies in the same boat; adversaries cooperating in a crisis", tags: ["협력", "위기"] },
  { word: "초지일관", hanja: "初志一貫", meaning: "처음에 품은 뜻을 끝까지 관철함. 흔들림 없이 처음 목표를 이룸", english: "Sticking to one's original intention; persevering to the end", tags: ["의지", "인내"] },
  { word: "일사불란", hanja: "一絲不亂", meaning: "한 올도 어지럽지 않음. 일의 처리가 질서 정연하여 흐트러짐이 없음", english: "Not a thread out of place; perfectly organized and orderly", tags: ["질서"] },
  { word: "명불허전", hanja: "名不虛傳", meaning: "이름이 헛되이 전해지지 않음. 명성이 실제 능력이나 실력과 부합함", english: "The name is not passed on in vain; worthy of one's reputation", tags: ["신뢰", "능력"] },
  { word: "이열치열", hanja: "以熱治熱", meaning: "열로써 열을 다스림. 어떤 문제를 같은 성질의 방법으로 대처함", english: "Fight fire with fire; using the same force to counter a problem", tags: ["지혜", "전략"] },
  { word: "촌철살인", hanja: "寸鐵殺人", meaning: "짧은 말 한마디가 사람을 죽임. 간결하고 날카로운 말 한마디로 핵심을 찌름", english: "Killing with a short sword; a sharp and concise remark that hits the mark", tags: ["말", "지혜"] },
  { word: "금과옥조", hanja: "金科玉條", meaning: "금과 옥 같은 조목. 반드시 지켜야 할 소중한 규범이나 규칙", english: "Rules sacred as gold and jade; inviolable principles", tags: ["도덕", "규범"] },
  { word: "고장난명", hanja: "孤掌難鳴", meaning: "한 손뼉만으로는 소리가 나지 않음. 혼자서 일을 이루기 어려움", english: "One hand cannot clap alone; you can't do it alone", tags: ["협력"] },
  { word: "사상누각", hanja: "沙上樓閣", meaning: "모래 위에 세운 누각. 튼튼한 기초 없이 세운 것은 쉽게 무너짐", english: "A house built on sand; something with no solid foundation", tags: ["판단", "기초"] },
  { word: "천신만고", hanja: "千辛萬苦", meaning: "천 가지 괴로움과 만 가지 고통. 온갖 어려움과 고생을 다 겪음", english: "A thousand trials and ten thousand hardships; going through great suffering", tags: ["인내", "고난"] },
  { word: "동상이몽", hanja: "同牀異夢", meaning: "같은 침대에서 다른 꿈을 꿈. 겉으로는 함께하는 것 같지만 속으로 다른 생각을 함", english: "Sharing a bed but dreaming different dreams; different intentions beneath the surface", tags: ["소통", "갈등"] },
  { word: "자강불식", hanja: "自强不息", meaning: "스스로 강해지기를 멈추지 않음. 끊임없이 노력하여 스스로를 발전시킴", english: "Striving constantly for self-improvement; never ceasing to strengthen oneself", tags: ["노력", "자립"] },
  { word: "전전긍긍", hanja: "戰戰兢兢", meaning: "두려워 떨며 몸을 움츠림. 불안하고 두려워서 몹시 조심하는 모양", english: "Trembling with fear; anxious and extremely cautious", tags: ["불안"] },
  { word: "감언이설", hanja: "甘言利說", meaning: "달콤한 말과 이로운 말로 꾀어냄. 상대방을 속이기 위한 교묘한 말", english: "Sweet words and flattery; honey-tongued deception", tags: ["기만", "말"] },
  { word: "무위도식", hanja: "無爲徒食", meaning: "하는 일 없이 밥만 먹음. 아무런 일도 하지 않고 놀고먹는 게으른 사람", english: "Eating without working; living as a freeloader", tags: ["태도", "게으름"] },
  { word: "권토중래", hanja: "捲土重來", meaning: "흙먼지를 말아 다시 옴. 한 번 실패하고 힘을 길러 다시 도전함", english: "Coming back with renewed strength; staging a comeback", tags: ["의지", "도전"] },
  { word: "결초보은", hanja: "結草報恩", meaning: "죽어서 풀로라도 은혜를 갚음. 받은 은혜를 잊지 않고 반드시 갚음", english: "Repaying a kindness even in death; never forgetting a debt of gratitude", tags: ["감사", "인성"] },
  { word: "함흥차사", hanja: "咸興差使", meaning: "함흥으로 간 차사처럼 소식이 없음. 심부름 간 사람이 돌아오지 않거나 연락이 없음", english: "Like a messenger who never returns; someone who goes and is never heard from again", tags: ["소통"] },
  { word: "오합지졸", hanja: "烏合之卒", meaning: "까마귀 떼처럼 무질서하게 모인 군사. 규율 없이 임시로 모인 무리", english: "A rabble; a disorganized mob with no discipline", tags: ["조직"] },
  { word: "일망타진", hanja: "一網打盡", meaning: "한 그물에 모두 잡음. 한꺼번에 모든 것을 잡거나 처리함", english: "Catching everything in one net; a complete sweep", tags: ["전략"] },
  { word: "각양각색", hanja: "各樣各色", meaning: "각각 모양도 다르고 색깔도 다름. 여러 가지로 다양함", english: "All shapes and colors; great variety", tags: ["다양성"] },
  { word: "이전투구", hanja: "泥田鬪狗", meaning: "진흙밭에서 싸우는 개. 체면이나 품위 없이 더럽게 다투는 모습", english: "Dogs fighting in a muddy field; a shameless and undignified fight", tags: ["갈등"] },
  { word: "내우외환", hanja: "內憂外患", meaning: "안의 근심과 밖의 환난. 나라나 조직이 안팎으로 어려움에 처함", english: "Troubles within and dangers without; beset by difficulties inside and out", tags: ["위기"] },
  { word: "배수진", hanja: "背水陣", meaning: "물을 등지고 진을 침. 절대 물러서지 않겠다는 각오로 마지막 승부를 거는 것", english: "Backs to the water; burning one's bridges and fighting to the last", tags: ["결의", "용기"] },
  { word: "작심삼일", hanja: "作心三日", meaning: "마음먹은 것이 사흘을 못 감. 결심이 오래 지속되지 않고 쉽게 포기함", english: "Resolution that lasts only three days; lack of follow-through", tags: ["의지"] },
  { word: "청산유수", hanja: "靑山流水", meaning: "청산에 흐르는 물처럼 막힘이 없음. 말이나 글이 막힘없이 거침없이 나옴", english: "Words flowing like a clear mountain stream; eloquent and fluent speech", tags: ["말"] },
  { word: "자화자찬", hanja: "自畵自讚", meaning: "자기가 그린 그림을 자기가 칭찬함. 자신의 것을 스스로 훌륭하다고 자랑함", english: "Self-praise; blowing one's own trumpet", tags: ["태도"] },
  { word: "천차만별", hanja: "千差萬別", meaning: "천 가지가 다르고 만 가지가 다름. 사물이 매우 다양하여 차이가 많음", english: "A thousand differences and ten thousand varieties; immense diversity", tags: ["다양성"] },
  { word: "진퇴양난", hanja: "進退兩難", meaning: "나아가기도 물러서기도 어려운 처지. 이러지도 저러지도 못하는 딜레마", english: "Caught between a rock and a hard place; unable to advance or retreat", tags: ["위기", "갈등"] },
  { word: "전광석화", hanja: "電光石火", meaning: "번개와 부싯돌의 불처럼 매우 빠름. 순식간에 일어나는 매우 빠른 일", english: "Swift as lightning and sparks; incredibly fast", tags: ["속도"] },
  { word: "파안대소", hanja: "破顔大笑", meaning: "얼굴이 환하게 크게 소리 내어 웃음. 매우 유쾌하게 크게 웃음", english: "Bursting into hearty laughter; a broad grin breaking across the face", tags: ["감정"] },
  { word: "일목요연", hanja: "一目瞭然", meaning: "한눈에 분명히 보임. 복잡한 내용이 한눈에 들어올 만큼 명확함", english: "Clear at a glance; self-evident and easy to understand", tags: ["지혜"] },
  { word: "선공후사", hanja: "先公後私", meaning: "공적인 일을 먼저 하고 사적인 일은 나중에 함. 공익을 우선시하는 자세", english: "Public duty before private interest; putting the community first", tags: ["도덕", "인성"] },
  { word: "논공행상", hanja: "論功行賞", meaning: "공을 논하여 상을 줌. 세운 공적에 따라 적절히 대우하고 보상함", english: "Rewarding according to merit; giving credit where credit is due", tags: ["공정"] },
  { word: "일이관지", hanja: "一以貫之", meaning: "하나의 원리로 일관되게 꿰뚫음. 처음부터 끝까지 하나의 원칙으로 일관함", english: "Consistent throughout; guided by a single principle from start to finish", tags: ["일관성"] },
  { word: "주마가편", hanja: "走馬加鞭", meaning: "달리는 말에 채찍을 더함. 잘 하고 있는 사람을 더욱 독려하거나 박차를 가함", english: "Whipping a galloping horse; urging on what is already going well", tags: ["노력", "격려"] },
  { word: "비일비재", hanja: "非一非再", meaning: "한두 번이 아님. 어떤 일이 매우 자주 반복적으로 일어남", english: "Not just once or twice; happening very often", tags: ["반복"] },
  { word: "불가사의", hanja: "不可思議", meaning: "생각으로는 알 수 없는 오묘한 것. 이해하거나 설명하기 어려운 신비한 일", english: "Beyond comprehension; mysterious and inexplicable", tags: ["신비"] },
  { word: "사족", hanja: "蛇足", meaning: "뱀에 발을 그리는 것. 쓸데없는 것을 덧붙여 오히려 일을 그르침", english: "Adding legs to a snake; an unnecessary addition that spoils things", tags: ["판단"] },
  { word: "삼성오신", hanja: "三省吾身", meaning: "하루에 세 번 자신을 돌아봄. 충성, 신의, 학습을 매일 스스로 점검함", english: "Examining oneself three times a day; daily self-reflection", tags: ["자기계발", "도덕"] },
  { word: "약방감초", hanja: "藥房甘草", meaning: "약방에 빠지지 않는 감초. 어떤 일에나 빠지지 않고 끼는 사람이나 사물", english: "Licorice in every prescription; indispensable in any situation", tags: ["인간관계"] },
  { word: "오비삼척", hanja: "吾鼻三尺", meaning: "내 코가 석 자. 자신의 처지도 어렵다는 뜻", english: "My own nose is three feet long; too busy with my own troubles to help others", tags: ["처지"] },
  { word: "우도할계", hanja: "牛刀割鷄", meaning: "소 잡는 칼로 닭을 자름. 작은 일에 지나치게 큰 수단을 씀", english: "Using a butcher's knife to kill a chicken; overkill", tags: ["판단"] },
  { word: "천하태평", hanja: "天下太平", meaning: "세상이 아무 걱정 없이 평온함. 또는 근심 없이 태평하게 사는 모습", english: "Peace under heaven; carefree and untroubled", tags: ["평화", "여유"] },
  { word: "입신양명", hanja: "立身揚名", meaning: "사회적으로 성공하여 이름을 높임. 뛰어난 성취로 명예로운 이름을 남김", english: "Establishing oneself and making a name; achieving fame and success", tags: ["성공", "명예"] },
  { word: "독야청청", hanja: "獨也靑靑", meaning: "홀로 푸르게 지냄. 외로운 환경에서도 올바름을 지키며 고고하게 살아감", english: "Evergreen alone; maintaining integrity in isolation", tags: ["인성", "고독"] },
  { word: "막역지우", hanja: "莫逆之友", meaning: "서로 거스름이 없는 친구. 뜻이 잘 맞아 매우 친밀한 친구", english: "A friend with no barriers; a deeply compatible lifelong friend", tags: ["우정"] },
  { word: "금란지계", hanja: "金蘭之契", meaning: "금란같이 단단하고 난초같이 향기로운 사귐. 매우 굳고 아름다운 우정", english: "A bond as strong as gold and fragrant as orchid; a precious friendship", tags: ["우정"] },
  { word: "사필귀정", hanja: "事必歸正", meaning: "모든 일은 반드시 올바름으로 돌아감. 결국 옳고 그름이 밝혀짐", english: "All things must return to righteousness; justice prevails in the end", tags: ["정의"] },
  { word: "청출어람", hanja: "靑出於藍", meaning: "쪽에서 나온 파란색이 쪽빛보다 더 파람 → 제자가 스승보다 뛰어남", english: "The student surpasses the teacher", tags: ["성장", "배움"] },
  { word: "주지육림", hanja: "酒池肉林", meaning: "술의 연못과 고기의 숲. 지나치게 호화롭고 방탕한 향락을 즐기는 것", english: "Lakes of wine and forests of meat; extreme extravagance and debauchery", tags: ["향락"] },
  { word: "문전성시", hanja: "門前成市", meaning: "문 앞이 시장을 이룸. 방문객이 끊이지 않아 매우 번성하고 붐빔", english: "A marketplace at one's door; a thriving, busy household", tags: ["번성"] },
  { word: "각골통한", hanja: "刻骨痛恨", meaning: "뼈에 새겨진 아픔과 원한. 뼛속 깊이 맺힌 원한과 통분", english: "Resentment carved into the bone; deep-seated, undying grudge", tags: ["원한", "감정"] },
];

export const SODAM_DATA: SodamEntry[] = [
  { sodam: "가는 말이 고와야 오는 말이 곱다", meaning: "남에게 잘 대해야 자신도 좋은 대우를 받는다", english: "Treat others as you wish to be treated", tags: ["인간관계", "배려"] },
  { sodam: "고생 끝에 낙이 온다", meaning: "힘든 일을 겪고 나면 즐거운 일이 따라온다", english: "No pain, no gain", tags: ["인내", "희망"] },
  { sodam: "공든 탑이 무너지랴", meaning: "정성껏 쌓은 것은 쉽게 무너지지 않는다", english: "Hard work pays off; what is built with care endures", tags: ["노력"] },
  { sodam: "낮말은 새가 듣고 밤말은 쥐가 듣는다", meaning: "말은 항상 조심해야 한다. 비밀은 없다", english: "Walls have ears; be careful what you say", tags: ["조심", "말"] },
  { sodam: "하늘이 무너져도 솟아날 구멍이 있다", meaning: "아무리 어려운 상황에서도 살아날 방도가 있다", english: "Every cloud has a silver lining", tags: ["희망"] },
  { sodam: "세 살 버릇 여든까지 간다", meaning: "어릴 때 몸에 밴 습관은 늙어서도 쉽게 고치지 못한다", english: "Old habits die hard", tags: ["습관", "교육"] },
  { sodam: "원숭이도 나무에서 떨어진다", meaning: "아무리 능숙한 사람도 실수할 수 있다", english: "Even Homer sometimes nods; nobody is perfect", tags: ["실수"] },
  { sodam: "호랑이도 제 말 하면 온다", meaning: "누군가의 이야기를 하면 마침 그 사람이 나타난다", english: "Talk of the devil and he shall appear", tags: ["우연"] },
  { sodam: "발 없는 말이 천 리 간다", meaning: "말은 아무리 먼 곳에도 금방 전해진다. 말 조심해라", english: "Words have wings; news travels fast", tags: ["말", "조심"] },
  { sodam: "배보다 배꼽이 크다", meaning: "기본보다 부수적인 것이 더 커지거나 중요해진다", english: "The tail wagging the dog", tags: ["균형"] },
  { sodam: "빈 수레가 요란하다", meaning: "아는 것이 없는 사람이 오히려 더 떠들어댄다", english: "Empty vessels make the most noise", tags: ["겸손"] },
  { sodam: "아 다르고 어 다르다", meaning: "같은 내용이라도 표현에 따라 전혀 다르게 들린다", english: "It's not what you say but how you say it", tags: ["말", "소통"] },
  { sodam: "될성부른 나무는 떡잎부터 알아본다", meaning: "장래가 기대되는 사람은 어릴 때부터 그 됨됨이가 보인다", english: "Great oaks from little acorns grow; talent shows early", tags: ["재능"] },
  { sodam: "지렁이도 밟으면 꿈틀한다", meaning: "아무리 약한 존재도 한계를 넘으면 반발한다", english: "Even a worm will turn; push anyone too far and they will react", tags: ["인내", "반발"] },
  { sodam: "꿩 먹고 알 먹는다", meaning: "한 가지 일로 두 가지 이득을 본다", english: "Kill two birds with one stone", tags: ["효율"] },
  { sodam: "소 잃고 외양간 고친다", meaning: "일이 이미 잘못된 후에야 뒤늦게 대책을 세운다", english: "Locking the stable door after the horse has bolted", tags: ["준비", "후회"] },
  { sodam: "티끌 모아 태산", meaning: "아주 작은 것도 모이면 큰 것이 된다", english: "Many a mickle makes a muckle; every little bit counts", tags: ["노력", "절약"] },
  { sodam: "굴러온 돌이 박힌 돌 뺀다", meaning: "나중에 온 사람이 먼저 있던 사람의 자리를 빼앗는다", english: "The newcomer takes over", tags: ["인간관계"] },
  { sodam: "말 한마디에 천 냥 빚도 갚는다", meaning: "말을 잘하면 어렵고 큰 문제도 해결할 수 있다", english: "A word fitly spoken is like gold", tags: ["말", "지혜"] },
  { sodam: "우물 안 개구리", meaning: "좁은 경험과 지식으로 세상 전체를 판단하는 사람", english: "A frog in a well; having a narrow worldview", tags: ["견문", "겸손"] },
  { sodam: "콩 심은 데 콩 나고 팥 심은 데 팥 난다", meaning: "원인에 따라 결과가 나타난다. 뿌린 대로 거둔다", english: "You reap what you sow", tags: ["인과"] },
  { sodam: "도둑이 제 발 저리다", meaning: "죄를 지은 사람이 탄로날까 봐 두려워 스스로 불안해한다", english: "A guilty conscience needs no accuser", tags: ["양심"] },
  { sodam: "등잔 밑이 어둡다", meaning: "가장 가까이에 있는 것을 오히려 모른다", english: "The darkest place is under the candlestick", tags: ["맹점", "주의"] },
  { sodam: "뛰는 놈 위에 나는 놈 있다", meaning: "잘 하는 사람 위에 더 잘 하는 사람이 있다. 교만하지 말아라", english: "There is always someone better than you; pride comes before a fall", tags: ["겸손"] },
  { sodam: "개천에서 용 난다", meaning: "변변치 않은 환경에서 뛰어난 인물이 난다", english: "A diamond in the rough; rising from humble beginnings", tags: ["성공", "희망"] },
  { sodam: "닭 잡아먹고 오리발 내민다", meaning: "잘못을 저지르고 엉뚱한 것으로 속이려 한다", english: "Cover up wrongdoing with a lame excuse", tags: ["정직", "기만"] },
  { sodam: "가랑비에 옷 젖는다", meaning: "사소한 것이라도 자꾸 쌓이면 큰 영향을 미친다", english: "Dripping water hollows out a stone", tags: ["지속성"] },
  { sodam: "모로 가도 서울만 가면 된다", meaning: "방법이 어떻든 목적만 이루면 된다", english: "The end justifies the means; any road will do if you don't know where you're going", tags: ["목표"] },
  { sodam: "사공이 많으면 배가 산으로 간다", meaning: "지휘하는 사람이 많으면 일이 엉뚱한 방향으로 흐른다", english: "Too many cooks spoil the broth", tags: ["리더십", "협력"] },
  { sodam: "시작이 반이다", meaning: "무슨 일이든 시작만 하면 절반은 한 것이나 마찬가지다", english: "Well begun is half done", tags: ["실행", "노력"] },
  { sodam: "열 번 찍어 안 넘어가는 나무 없다", meaning: "무슨 일이든 열심히 거듭 노력하면 이룰 수 있다", english: "Perseverance wins in the end", tags: ["노력", "인내"] },
  { sodam: "쥐구멍에도 볕 들 날 있다", meaning: "아무리 불행한 사람도 운이 트이는 때가 있다", english: "Every dog has its day", tags: ["희망"] },
  { sodam: "아니 땐 굴뚝에 연기 나랴", meaning: "원인 없는 결과는 없다. 소문에는 반드시 이유가 있다", english: "Where there's smoke there's fire", tags: ["인과"] },
  { sodam: "작은 고추가 더 맵다", meaning: "작고 약해 보이는 것이 오히려 더 강하거나 능력이 있다", english: "Big things come in small packages", tags: ["편견"] },
  { sodam: "자라 보고 놀란 가슴 솥뚜껑 보고 놀란다", meaning: "한 번 놀란 경험 때문에 비슷한 것만 봐도 무서워한다", english: "Once bitten, twice shy", tags: ["트라우마", "조심"] },
  { sodam: "바늘 도둑이 소 도둑 된다", meaning: "작은 잘못을 방치하면 결국 큰 잘못으로 커진다", english: "He that will steal a pin will steal a better thing", tags: ["도덕", "습관"] },
  { sodam: "하늘은 스스로 돕는 자를 돕는다", meaning: "자신이 노력하는 사람에게 하늘도 돕는다", english: "God helps those who help themselves", tags: ["노력", "자립"] },
  { sodam: "윗물이 맑아야 아랫물이 맑다", meaning: "윗사람이 모범을 보여야 아랫사람도 바르게 된다", english: "A fish rots from the head down; leadership sets the tone", tags: ["리더십", "모범"] },
  { sodam: "참을 인 자 셋이면 살인도 면한다", meaning: "인내하고 참으면 큰 화를 피할 수 있다", english: "Patience is a virtue; count to ten before acting", tags: ["인내", "절제"] },
  { sodam: "눈 가리고 아웅", meaning: "얕은 꾀로 남을 속이려 하지만 뻔히 드러남", english: "Pulling the wool over someone's eyes poorly", tags: ["기만", "속임"] },
  { sodam: "혹 떼러 갔다 혹 붙여 온다", meaning: "이익을 얻으려다가 오히려 손해를 보고 돌아온다", english: "Go for wool and come home shorn", tags: ["실패", "욕심"] },
  { sodam: "핑계 없는 무덤 없다", meaning: "어떤 잘못에도 변명은 항상 있다", english: "There is always an excuse", tags: ["책임"] },
  { sodam: "부뚜막의 소금도 집어넣어야 짜다", meaning: "아무리 좋은 조건이 갖춰져 있어도 실행해야 효과가 있다", english: "Knowledge without action is useless", tags: ["실행"] },
  { sodam: "세월이 약이다", meaning: "시간이 지나면 어떤 슬픔이나 고통도 차츰 나아진다", english: "Time heals all wounds", tags: ["치유", "인내"] },
  { sodam: "입이 열 개라도 할 말이 없다", meaning: "잘못이 너무 명백하여 아무리 변명해도 할 말이 없다", english: "No excuse can be made; caught red-handed", tags: ["책임"] },
  { sodam: "구르는 돌은 이끼가 안 낀다", meaning: "부지런히 활동하는 사람은 발전하고 기회를 잡는다", english: "A rolling stone gathers no moss", tags: ["노력", "활동"] },
  { sodam: "가는 날이 장날", meaning: "방문한 날이 마침 바쁜 날이거나, 공교롭게 딱 맞는 때", english: "Just my luck; arriving on the wrong (or right) day by coincidence", tags: ["우연"] },
  { sodam: "호미로 막을 것을 가래로 막는다", meaning: "작을 때 쉽게 처리할 수 있을 것을 내버려 두었다가 크게 애먹는다", english: "A stitch in time saves nine", tags: ["미리", "준비"] },
  { sodam: "까마귀 날자 배 떨어진다", meaning: "두 사건이 공교롭게 같은 때에 일어나 오해를 받다", english: "Guilty by coincidence; bad timing", tags: ["오해", "우연"] },
  { sodam: "열길 물속은 알아도 한 길 사람 속은 모른다", meaning: "물속 깊이는 알 수 있어도 사람 마음은 알기 어렵다", english: "You can know the depth of the sea but not the heart of a person", tags: ["인간관계", "신뢰"] },
  // ── 추가 100선 ──
  { sodam: "개구리 올챙이 적 생각 못 한다", meaning: "형편이 나아지면 어렵던 시절을 잊고 오만해진다", english: "The frog forgets it was once a tadpole; forgetting humble beginnings", tags: ["교만", "겸손"] },
  { sodam: "고양이 목에 방울 달기", meaning: "실행하기 어려운 계획을 의논하는 것. 이론은 좋지만 실천이 어려움", english: "Belling the cat; a plan that sounds good but is impossible to execute", tags: ["현실"] },
  { sodam: "굿이나 보고 떡이나 먹어라", meaning: "관계없는 일에 쓸데없이 참견하지 말라", english: "Mind your own business; watch the show and eat the rice cake", tags: ["태도"] },
  { sodam: "남의 떡이 커 보인다", meaning: "자기 것보다 남의 것이 더 좋아 보이는 심리", english: "The grass is always greener on the other side", tags: ["욕심", "비교"] },
  { sodam: "누워서 침 뱉기", meaning: "결국 자기에게 해가 되는 행동을 스스로 함", english: "Spitting while lying down; acting against one's own interests", tags: ["인과"] },
  { sodam: "달면 삼키고 쓰면 뱉는다", meaning: "이롭고 편리할 때만 취하고 그렇지 않으면 버리는 이기적 태도", english: "Swallow the sweet and spit out the bitter; purely self-serving", tags: ["이기심"] },
  { sodam: "돌다리도 두드려 보고 건너라", meaning: "아무리 확실해 보여도 다시 한번 확인하고 신중하게 행동하라", english: "Even a stone bridge should be tested before crossing; double-check everything", tags: ["신중", "준비"] },
  { sodam: "목마른 놈이 우물 판다", meaning: "필요를 느끼는 사람이 먼저 나서서 행동한다", english: "The thirsty one digs the well; the most motivated person takes action", tags: ["주도성", "실행"] },
  { sodam: "미꾸라지 한 마리가 온 웅덩이를 흐린다", meaning: "한 사람의 잘못된 행동이 전체 집단에 피해를 줌", english: "One mudfish muddies the whole pond; one bad apple spoils the bunch", tags: ["책임", "인간관계"] },
  { sodam: "벼는 익을수록 고개를 숙인다", meaning: "실력이 뛰어나고 성숙한 사람일수록 더 겸손하게 행동한다", english: "The riper the rice, the lower it bows; the wiser the person, the more humble", tags: ["겸손", "성장"] },
  { sodam: "병 주고 약 준다", meaning: "해를 끼친 뒤에 도와주는 척하는 이중적인 행동", english: "Giving the disease then the cure; causing harm and then offering help", tags: ["기만", "이중성"] },
  { sodam: "쇠귀에 경 읽기", meaning: "아무리 올바른 말을 해줘도 전혀 알아듣지 못하거나 받아들이지 않음", english: "Reading sutras to a cow; wasted advice on someone who won't listen", tags: ["소통"] },
  { sodam: "찬물도 위아래가 있다", meaning: "아무리 사소한 일이라도 지켜야 할 순서와 격식이 있음", english: "Even cold water has its hierarchy; everything has its proper order", tags: ["예의", "질서"] },
  { sodam: "콩으로 메주를 쑨다 해도 안 믿는다", meaning: "신뢰를 한 번 잃으면 올바른 말을 해도 믿어주지 않음", english: "Even saying you made doenjang from beans won't be believed; trust once lost is hard to regain", tags: ["신뢰"] },
  { sodam: "팔은 안으로 굽는다", meaning: "사람은 자연스럽게 자기와 가까운 편을 들게 되어 있음", english: "The arm bends inward; people naturally favor those close to them", tags: ["인간관계", "편애"] },
  { sodam: "하룻강아지 범 무서운 줄 모른다", meaning: "경험이 없는 사람이 두려운 것도 모르고 무모하게 덤빔", english: "A day-old puppy doesn't fear the tiger; naive boldness from inexperience", tags: ["무모", "경험"] },
  { sodam: "호랑이에게 물려가도 정신만 차리면 산다", meaning: "아무리 위험한 상황에서도 침착하게 정신 차리면 살길이 생긴다", english: "Even carried off by a tiger, keep your wits and you'll survive", tags: ["침착", "위기"] },
  { sodam: "귀에 걸면 귀걸이, 코에 걸면 코걸이", meaning: "같은 것도 해석하는 관점에 따라 전혀 다르게 적용됨", english: "An earring if it's on the ear, a nose ring if it's on the nose; it all depends on perspective", tags: ["관점"] },
  { sodam: "내 코가 석 자다", meaning: "자기 사정이 너무 어려워 남을 돌볼 여유조차 없음", english: "My own nose is three feet long; too much trouble of my own", tags: ["처지"] },
  { sodam: "말이 많으면 쓸 말이 없다", meaning: "말이 많은 사람은 정작 중요한 순간에 할 말이 없어짐", english: "Too many words leave nothing meaningful to say", tags: ["말", "절제"] },
  { sodam: "모난 돌이 정 맞는다", meaning: "지나치게 튀거나 까다롭게 행동하면 비판이나 불이익을 받게 됨", english: "The stone that sticks out gets chiseled; standing out invites criticism", tags: ["처세"] },
  { sodam: "백지장도 맞들면 낫다", meaning: "아무리 가벼운 일도 혼자보다 함께하는 것이 더 낫다", english: "Even a sheet of paper is easier to lift together; two heads are better than one", tags: ["협력"] },
  { sodam: "빛 좋은 개살구", meaning: "겉모습은 그럴싸해 보여도 실제 내용은 별로인 것", english: "A crab apple that looks good; all show and no substance", tags: ["겉과속"] },
  { sodam: "서당 개 삼 년이면 풍월을 읊는다", meaning: "어떤 환경에 오래 있으면 무엇이든 자연스럽게 익숙해진다", english: "Even a school dog learns to recite poetry after three years; you pick things up by being around them", tags: ["경험", "습관"] },
  { sodam: "소문난 잔치에 먹을 것 없다", meaning: "크게 소문난 것에 비해 실제로는 실속이 없는 경우가 많음", english: "The feast that's talked about has nothing to eat; all talk, no substance", tags: ["기대"] },
  { sodam: "수박 겉핥기", meaning: "겉만 훑고 깊이 있게 파고들지 않는 방식", english: "Licking the outside of a watermelon; a superficial approach", tags: ["집중"] },
  { sodam: "오르지 못할 나무는 쳐다보지도 마라", meaning: "자신의 능력 밖의 것은 처음부터 욕심 내지 말라", english: "Don't even look at a tree you cannot climb; don't covet what is beyond your reach", tags: ["욕심", "현실"] },
  { sodam: "옥에 티", meaning: "완벽한 것에 아주 작은 흠이 있는 것. 전체적으로 좋지만 한 가지 흠", english: "A flaw in jade; a small imperfection in something otherwise perfect", tags: ["완벽"] },
  { sodam: "지성이면 감천이다", meaning: "정성이 지극하면 하늘도 감동하여 도와준다", english: "True sincerity moves heaven; devotion will be rewarded", tags: ["노력", "희망"] },
  { sodam: "피는 물보다 진하다", meaning: "혈연관계는 어떤 다른 관계보다 가깝고 강하다", english: "Blood is thicker than water; family bonds are the strongest", tags: ["가족"] },
  { sodam: "호랑이 굴에 들어가야 호랑이 새끼를 잡는다", meaning: "위험을 무릅쓰고 뛰어들어야 큰 것을 얻을 수 있다", english: "You must enter the tiger's den to catch its cubs; no risk, no reward", tags: ["도전", "용기"] },
  { sodam: "가재는 게 편이다", meaning: "비슷한 처지나 종류끼리는 자연스럽게 서로 편을 들게 됨", english: "The crayfish sides with the crab; birds of a feather flock together", tags: ["인간관계"] },
  { sodam: "떡 줄 사람은 꿈도 안 꾸는데 김칫국부터 마신다", meaning: "아직 결정도 안 난 일을 미리 다 된 듯이 기대함", english: "Drinking kimchi soup before the rice cake is offered; counting chickens before they hatch", tags: ["기대", "희망"] },
  { sodam: "못된 송아지 엉덩이에 뿔 난다", meaning: "되지 못한 사람이 오히려 더 나대고 까불거리며 설침", english: "A bad calf grows horns on its rump; troublemakers show their worst side", tags: ["태도", "인성"] },
  { sodam: "물 들어올 때 노 저어라", meaning: "기회가 왔을 때 망설이지 말고 잡아야 한다", english: "Row when the tide is in; seize the opportunity when it comes", tags: ["기회", "실행"] },
  { sodam: "비 온 뒤에 땅이 굳어진다", meaning: "어려운 시련을 거치고 나면 오히려 더 강하고 단단해진다", english: "After rain the ground hardens; adversity makes you stronger", tags: ["인내", "성장"] },
  { sodam: "젊어서 고생은 사서도 한다", meaning: "젊을 때의 고생은 자신을 단련시키는 경험이 되므로 두려워할 필요 없다", english: "Buy hardship when you're young; youthful struggles build character", tags: ["노력", "성장"] },
  { sodam: "좋은 약은 입에 쓰다", meaning: "진심 어린 충고는 듣기에 불편하지만 결국 도움이 된다", english: "Good medicine is bitter to the taste; honest advice is hard to hear but helpful", tags: ["충고", "지혜"] },
  { sodam: "하나를 보면 열을 안다", meaning: "한 가지 면을 보면 나머지 전체를 미루어 짐작할 수 있다", english: "See one thing and know ten; a single glimpse tells the whole story", tags: ["지혜", "관찰"] },
  { sodam: "제 눈에 안경이다", meaning: "좋아하는 사람은 어떤 단점도 보이지 않고 다 좋아 보임", english: "Beauty is in the eye of the beholder; love is blind", tags: ["사랑", "편견"] },
  { sodam: "이웃사촌", meaning: "가까이 사는 이웃이 멀리 사는 친척보다 더 가깝고 요긴하다", english: "A neighbor is nearer than a distant cousin; proximity creates kinship", tags: ["인간관계", "이웃"] },
  { sodam: "고래 싸움에 새우 등 터진다", meaning: "강자들이 싸울 때 아무 관계도 없는 약자만 피해를 봄", english: "When whales fight, the shrimp's back breaks; bystanders suffer when the powerful clash", tags: ["약자", "피해"] },
  { sodam: "첫술에 배부르랴", meaning: "처음 한 번에 만족스러운 결과가 나올 수 없으니 차근차근 노력해야 한다", english: "You can't be full after just one spoonful; don't expect immediate results", tags: ["인내", "노력"] },
  { sodam: "이 없으면 잇몸으로", meaning: "없으면 있는 것으로, 불완전하더라도 현재 가진 것으로 해결함", english: "If you have no teeth, use your gums; make do with what you have", tags: ["응용", "실행"] },
  { sodam: "입은 삐뚤어져도 말은 바로 해라", meaning: "어떤 상황에서도 정직하고 바르게 말해야 한다", english: "Even with a crooked mouth, speak straight; always speak the truth", tags: ["정직", "말"] },
  { sodam: "두 마리 토끼를 잡으려다 둘 다 놓친다", meaning: "욕심이 지나치면 두 가지 다 얻으려다 아무것도 못 얻음", english: "Chasing two rabbits catches neither; too much greed leads to nothing", tags: ["욕심", "집중"] },
  { sodam: "떡 본 김에 제사 지낸다", meaning: "기회가 생긴 김에 해야 할 일을 함께 해치운다", english: "Holding a memorial service since you have rice cakes anyway; seizing a convenient opportunity", tags: ["기회", "효율"] },
  { sodam: "낙숫물이 댓돌을 뚫는다", meaning: "꾸준한 노력이 아무리 단단한 것도 결국 뚫을 수 있다", english: "Dripping eaves water wears through stone; constant effort conquers all", tags: ["노력", "인내"] },
  { sodam: "길이 아니면 가지 말고, 말이 아니면 듣지 마라", meaning: "올바른 것만을 따르고, 그릇된 것은 받아들이지 말아야 한다", english: "Don't walk a path that isn't a path; follow only what is right", tags: ["도덕"] },
  { sodam: "믿는 도끼에 발등 찍힌다", meaning: "가장 믿었던 사람에게 오히려 배신을 당하거나 예상치 못한 피해를 봄", english: "The axe you trusted cuts your foot; betrayed by someone you counted on", tags: ["신뢰", "배신"] },
  { sodam: "천 리 길도 한 걸음부터", meaning: "아무리 크고 먼 목표라도 작은 첫 걸음부터 시작된다", english: "A journey of a thousand miles begins with a single step", tags: ["시작", "실행"] },
  { sodam: "아는 길도 물어 가라", meaning: "잘 알고 있다고 해도 다시 한 번 확인하며 신중하게 행동하라", english: "Even on a familiar road, ask for directions; always double-check", tags: ["신중"] },
  { sodam: "원수는 외나무다리에서 만난다", meaning: "피하고 싶은 사람이나 상황을 피할 수 없는 곳에서 반드시 마주침", english: "Enemies always meet on a narrow bridge; you can't avoid your nemesis", tags: ["인과", "우연"] },
  { sodam: "제 살 깎기", meaning: "자신에게 직접 손해가 되는 짓을 스스로 하는 어리석음", english: "Cutting your own flesh; working against your own interests", tags: ["판단"] },
  { sodam: "구관이 명관이다", meaning: "새 사람이 꼭 나은 것이 아니라 오히려 전임자가 더 나을 수 있음", english: "The old official is the good official; familiarity breeds competence", tags: ["경험"] },
  { sodam: "낫 놓고 기역 자도 모른다", meaning: "낫 모양이 바로 기역인데도 글자를 모름. 극도로 무식함을 이름", english: "Can't recognize the letter 'g' even with a sickle in hand; completely illiterate", tags: ["무지"] },
  { sodam: "약방에 감초", meaning: "어떤 자리나 모임에나 빠지지 않고 끼는 사람이나 사물", english: "Licorice in the medicine chest; someone who turns up everywhere", tags: ["인간관계"] },
  { sodam: "제 버릇 개 줄까", meaning: "한번 몸에 밴 나쁜 습관은 고치기가 몹시 어렵다", english: "Would you give your bad habits to a dog? Bad habits die hard", tags: ["습관"] },
  { sodam: "공짜라면 양잿물도 마신다", meaning: "공짜라면 나쁜 것도 마다하지 않는 지나친 공짜 심리", english: "If it's free, I'd even drink lye; unable to resist anything free", tags: ["욕심"] },
  { sodam: "급할수록 돌아가라", meaning: "서두를수록 실수가 생기니, 급할 때일수록 차분히 돌아서 가라", english: "The more you hurry, the longer way round; haste makes waste", tags: ["신중", "인내"] },
  { sodam: "가는 정이 있어야 오는 정이 있다", meaning: "자신이 먼저 상대에게 잘 대해 주어야 상대도 잘 대해 준다", english: "Give affection to receive affection; you get what you give", tags: ["인간관계", "배려"] },
  { sodam: "배고픈 것은 참아도 배 아픈 것은 못 참는다", meaning: "자신의 고통은 참을 수 있어도 남이 잘되는 것이 더 시기가 됨", english: "I can bear my own hunger but not another's full belly; harder to bear others' success than one's own hardship", tags: ["질투"] },
  { sodam: "실패는 성공의 어머니다", meaning: "실패를 통해 교훈을 얻고 결국 성공에 이를 수 있다", english: "Failure is the mother of success; learn from your mistakes", tags: ["성장", "도전"] },
  { sodam: "보기 좋은 떡이 먹기도 좋다", meaning: "겉모양이 좋으면 내용도 좋은 경우가 많다. 첫인상도 중요함", english: "A good-looking rice cake tastes good too; appearances often reflect substance", tags: ["첫인상"] },
  { sodam: "아닌 밤중에 홍두깨", meaning: "갑자기 뜬금없이 뜻밖의 말이나 행동을 함", english: "A laundry bat in the middle of the night; something completely out of the blue", tags: ["당혹", "우연"] },
  { sodam: "어물전 망신은 꼴뚜기가 시킨다", meaning: "못난 것 하나 때문에 집단 전체가 망신을 당함", english: "The squid disgraces the fish market; one bad member ruins the group's reputation", tags: ["책임", "인성"] },
  { sodam: "입술이 없으면 이가 시리다", meaning: "서로 의지하는 관계에서 한 쪽이 없어지면 남은 쪽도 힘들어짐", english: "Without lips the teeth feel cold; when one is lost, the other suffers too", tags: ["의존", "인간관계"] },
  { sodam: "죄는 미워해도 사람은 미워하지 마라", meaning: "잘못을 비판하되, 잘못을 저지른 사람 자체를 미워하지는 말라", english: "Hate the sin but not the sinner; condemn the act, not the person", tags: ["도덕", "이해"] },
  { sodam: "혀 끝이 칼보다 날카롭다", meaning: "날카로운 말 한마디가 칼보다 더 깊은 상처를 줄 수 있다", english: "The tip of the tongue is sharper than a sword; words can wound more than weapons", tags: ["말"] },
  { sodam: "그림의 떡", meaning: "보기만 하고 실제로는 가질 수 없는 것", english: "A rice cake in a picture; something desirable but unattainable", tags: ["욕망"] },
  { sodam: "산 넘어 산", meaning: "하나의 어려움을 해결하면 또 다른 어려움이 기다리고 있음", english: "Mountain after mountain; as soon as one problem is solved, another appears", tags: ["고난"] },
  { sodam: "잘되면 제 덕, 못되면 조상 탓", meaning: "일이 잘되면 자기 덕분이라 하고 못되면 남의 탓으로 돌림", english: "Credit yourself for success, blame your ancestors for failure; taking credit but deflecting blame", tags: ["책임", "태도"] },
  { sodam: "참는 것이 이기는 것이다", meaning: "분하더라도 인내하고 참으면 결국 그것이 이기는 길이 된다", english: "He who endures wins; patience is the greatest victory", tags: ["인내"] },
  { sodam: "말 타면 종 두고 싶다", meaning: "한 가지 이득을 얻으면 욕심이 생겨 더 큰 것을 원하게 됨", english: "Ride a horse and you want a servant; greed grows with satisfaction", tags: ["욕심"] },
  { sodam: "칭찬은 고래도 춤추게 한다", meaning: "칭찬은 어떤 대상이라도 행동하게 만들 만큼 강력한 동기부여가 됨", english: "Praise can make even a whale dance; recognition motivates anyone", tags: ["칭찬", "관계"] },
  { sodam: "새도 가지를 가려서 앉는다", meaning: "사람도 자신이 있을 자리와 함께 할 사람을 신중히 선택해야 한다", english: "Even birds choose their branch carefully; choose your place and companions wisely", tags: ["선택", "처세"] },
  { sodam: "손뼉도 마주쳐야 소리가 난다", meaning: "어떤 일이든 혼자서만 해서는 이루기 어렵고 협력이 필요하다", english: "Even clapping needs two hands; cooperation is essential", tags: ["협력"] },
  { sodam: "이왕이면 다홍치마", meaning: "같은 조건이라면 더 좋은 것을 선택하는 것이 당연함", english: "Better a red skirt if you can afford it; choose the better option when possible", tags: ["선택"] },
  { sodam: "친구 따라 강남 간다", meaning: "자기 주관 없이 남이 하는 것을 그냥 따라 함", english: "Following a friend to Gangnam; going along without having one's own reason", tags: ["주체성"] },
  { sodam: "사람은 쓸 때 안다", meaning: "사람의 진면목과 진가는 어려운 상황이 되어야 드러난다", english: "A man shows his worth when he's needed; you know a person when you need them", tags: ["인간관계"] },
  { sodam: "입술이 두꺼울수록 밥은 많이 먹는다", meaning: "뻔뻔하고 염치없는 사람이 오히려 더 많이 챙겨간다", english: "Thick lips eat more rice; the shameless get more", tags: ["뻔뻔"] },
  { sodam: "게 눈 감추듯", meaning: "눈 깜짝할 사이에 음식 등을 매우 빨리 먹어 치우는 것", english: "Like a crab hiding its eyes; vanishing in the blink of an eye", tags: ["속도"] },
  { sodam: "도랑 치고 가재 잡는다", meaning: "하나의 일을 하면서 동시에 다른 이익을 얻음", english: "Clean the ditch and catch the crayfish; accomplishing two things at once", tags: ["효율"] },
  { sodam: "웃음이 보약이다", meaning: "즐겁게 웃는 것 자체가 건강에 가장 좋은 보약이 된다", english: "Laughter is the best medicine; a cheerful heart heals", tags: ["건강", "긍정"] },
  { sodam: "뒤로 넘어져도 코가 깨진다", meaning: "재수가 없는 사람은 어디서나 손해를 보거나 운이 나쁜 일이 생긴다", english: "Even falling backward you bruise your nose; unlucky in everything", tags: ["불운"] },
  { sodam: "배부른 소리 한다", meaning: "형편이 좋아 불필요한 투정을 부리거나 여유 있는 말을 함", english: "Talking on a full stomach; complaining when well-off", tags: ["태도"] },
  { sodam: "끝이 좋으면 다 좋다", meaning: "과정이 어떻든 결과가 좋게 끝나면 결국 좋은 것으로 평가됨", english: "All's well that ends well; a good ending makes everything good", tags: ["결과"] },
  { sodam: "나무를 보지 말고 숲을 봐라", meaning: "세세한 부분에 집착하지 말고 전체적인 큰 그림을 보아야 한다", english: "Don't look at the trees, see the forest; think big-picture", tags: ["관점", "지혜"] },
  { sodam: "부부 싸움은 칼로 물 베기", meaning: "부부 싸움은 아무리 심해도 금방 화해하게 된다", english: "A marital quarrel is like slicing water with a knife; lovers always make up", tags: ["가족", "화해"] },
  { sodam: "하늘 높은 줄 모른다", meaning: "자신의 분수를 모르고 오만하게 굴거나 지나치게 잘난 척함", english: "Doesn't know how high the sky is; arrogant and unaware of one's limits", tags: ["교만"] },
  { sodam: "도끼를 갈아 바늘을 만든다", meaning: "아무리 어렵고 큰 것도 꾸준히 노력하면 원하는 결과를 얻는다", english: "Grinding an axe into a needle; persistent effort achieves anything", tags: ["노력", "인내"] },
  { sodam: "되로 주고 말로 받는다", meaning: "적게 줬는데 그보다 훨씬 많이 돌아오거나, 작은 도움에 과도한 보답을 받음", english: "Give a pint, get a bushel; a small kindness returned many times over", tags: ["인과"] },
  { sodam: "세상에 공짜는 없다", meaning: "모든 것에는 반드시 그에 상응하는 대가가 따른다", english: "There's no free lunch; everything has a price", tags: ["현실"] },
  { sodam: "임시방편", meaning: "근본적인 해결 없이 당장의 상황만 모면하려는 임기응변적 처리", english: "A stopgap measure; a temporary fix that doesn't address the root problem", tags: ["판단"] },
  { sodam: "작은 씨앗이 큰 나무가 된다", meaning: "아주 작은 시작이 결국 크게 성장할 수 있다", english: "A tiny seed grows into a great tree; small beginnings can lead to great things", tags: ["성장", "희망"] },
  { sodam: "바보도 제 밥그릇은 챙긴다", meaning: "아무리 어리석은 사람도 자기 이익만큼은 확실히 챙긴다", english: "Even a fool looks after his own bowl; self-interest is universal", tags: ["이기심"] },
  { sodam: "맞는 말도 때와 장소를 가려서 해라", meaning: "옳은 말이라도 때와 상황을 가려서 해야 효과가 있다", english: "Even true words need the right time and place; timing is everything", tags: ["말", "지혜"] },
  { sodam: "항상 웃는 사람이 이긴다", meaning: "어려운 상황에서도 긍정적이고 여유 있는 태도가 결국 성공으로 이어짐 (현대 속담)", english: "The one who keeps smiling wins; positivity is its own victory", tags: ["긍정"] },
  { sodam: "다된 밥에 재 뿌리기", meaning: "거의 다 완성된 일을 망쳐버리는 행동을 함", english: "Throwing ash in the cooked rice; ruining something just as it's finished", tags: ["방해"] },
  { sodam: "낮말은 새가 듣고 밤말은 쥐가 듣는다", meaning: "어떤 말이라도 반드시 누군가에게 전해지므로 항상 말 조심해야 함", english: "Birds hear day words, mice hear night words; someone is always listening", tags: ["조심", "말"] },
  { sodam: "부지런한 새가 벌레를 잡는다", meaning: "일찍 일어나 부지런히 움직이는 사람이 기회와 성과를 잡는다", english: "The early bird catches the worm; diligence reaps rewards", tags: ["노력", "부지런함"] },
];
