export interface GosaEntry {
  word: string;
  hanja: string;
  meaning: string;
  english: string;
  tags?: string[];
}

export interface SodamEntry {
  sodam: string;
  meaning: string;
  english: string;
  tags?: string[];
}

export const GOSA_DATA: GosaEntry[] = [
  { word: "일석이조", hanja: "一石二鳥", meaning: "돌 하나로 새 두 마리를 잡는다는 뜻으로, 하나의 행동으로 두 가지 이익을 얻음", english: "Kill two birds with one stone", tags: ["지혜", "효율"] },
  { word: "과유불급", hanja: "過猶不及", meaning: "지나친 것은 부족함만 못하다. 적당한 것이 최선임", english: "Too much is as bad as too little", tags: ["절제"] },
  { word: "청출어람", hanja: "靑出於藍", meaning: "쪽에서 나온 파란색이 쪽빛보다 더 파람 → 제자가 스승보다 뛰어남", english: "The student surpasses the teacher", tags: ["성장", "배움"] },
  { word: "살신성인", hanja: "殺身成仁", meaning: "자신의 몸을 희생하여 인(仁)을 이룸. 대의를 위해 자신을 바침", english: "Sacrifice oneself for righteousness", tags: ["희생", "용기"] },
  { word: "온고지신", hanja: "溫故知新", meaning: "옛것을 익히고 그것으로 새것을 앎. 역사와 전통에서 배움", english: "Review the old and learn the new", tags: ["배움", "지혜"] },
  { word: "오십보백보", hanja: "五十步百步", meaning: "오십 보 도망간 자가 백 보 도망간 자를 비웃음 → 본질적 차이가 없음", english: "Six of one, half a dozen of the other", tags: ["비교"] },
  { word: "유유상종", hanja: "類類相從", meaning: "같은 무리끼리 서로 어울림. 성격·처지가 비슷한 사람들이 모임", english: "Birds of a feather flock together", tags: ["인간관계"] },
  { word: "동고동락", hanja: "同苦同樂", meaning: "괴로움과 즐거움을 함께 나눔", english: "Share joys and sorrows together", tags: ["인간관계", "우정"] },
  { word: "사면초가", hanja: "四面楚歌", meaning: "사방이 적의 노래 소리로 가득함 → 고립무원의 위험 상황", english: "Surrounded by enemies on all sides", tags: ["위기"] },
  { word: "막상막하", hanja: "莫上莫下", meaning: "위도 아래도 없다는 뜻으로, 서로 우열을 가리기 어려울 만큼 비슷함", english: "Neck and neck; evenly matched", tags: ["비교"] },
  { word: "전화위복", hanja: "轉禍爲福", meaning: "재화(災禍)가 바뀌어 복이 됨. 나쁜 일이 결국 좋은 결과로 이어짐", english: "A blessing in disguise", tags: ["긍정", "희망"] },
  { word: "호사다마", hanja: "好事多魔", meaning: "좋은 일에는 방해가 많음. 잘 될 때일수록 조심해야 함", english: "Good things often come with obstacles", tags: ["조심"] },
  { word: "동병상련", hanja: "同病相憐", meaning: "같은 병을 앓는 사람끼리 서로 불쌍히 여김. 같은 처지에서 생기는 공감", english: "Misery loves company", tags: ["공감", "인간관계"] },
  { word: "이심전심", hanja: "以心傳心", meaning: "마음에서 마음으로 전해짐. 말하지 않아도 서로 통함", english: "Heart to heart; unspoken understanding", tags: ["소통", "우정"] },
  { word: "백문불여일견", hanja: "百聞不如一見", meaning: "백 번 듣는 것이 한 번 보는 것만 못함. 직접 경험이 중요함", english: "Seeing is believing", tags: ["경험", "지혜"] },
  { word: "대기만성", hanja: "大器晩成", meaning: "큰 그릇은 늦게 이루어짐 → 크게 될 사람은 늦게 성공함", english: "Great talents mature slowly", tags: ["성장", "인내"] },
  { word: "괄목상대", hanja: "刮目相對", meaning: "눈을 비비고 다시 보다 → 상대의 발전이 놀라울 정도임", english: "Look at someone with fresh eyes; admire remarkable progress", tags: ["성장", "발전"] },
  { word: "표리부동", hanja: "表裏不同", meaning: "겉과 속이 다름. 말과 행동이 일치하지 않음", english: "Two-faced; saying one thing and doing another", tags: ["인성"] },
  { word: "군계일학", hanja: "群鷄一鶴", meaning: "닭 무리 중의 학 한 마리 → 여러 사람 중에 특별히 뛰어난 사람", english: "A crane among chickens; standing out from the crowd", tags: ["탁월함"] },
  { word: "금상첨화", hanja: "錦上添花", meaning: "비단 위에 꽃을 더함 → 좋은 일에 더 좋은 일이 겹침", english: "The icing on the cake", tags: ["행운"] },
  { word: "설상가상", hanja: "雪上加霜", meaning: "눈 위에 서리가 내림 → 불행이 잇따라 겹침", english: "Adding insult to injury; from bad to worse", tags: ["불운", "위기"] },
  { word: "청천벽력", hanja: "靑天霹靂", meaning: "맑은 하늘에 날벼락 → 뜻밖의 큰 충격이나 변고", english: "A bolt from the blue; unexpected shock", tags: ["충격"] },
  { word: "동문서답", hanja: "東問西答", meaning: "동쪽을 물으니 서쪽을 답함 → 질문의 요점을 빗나간 엉뚱한 대답", english: "Answering a question with an irrelevant answer", tags: ["소통"] },
  { word: "임기응변", hanja: "臨機應變", meaning: "때와 형편에 따라 적절하게 대처함", english: "Adapting to the situation; quick thinking", tags: ["지혜", "대처"] },
  { word: "칠전팔기", hanja: "七顚八起", meaning: "일곱 번 넘어지고 여덟 번 일어남 → 어떤 실패에도 굴하지 않는 불굴의 의지", english: "Fall seven times, stand up eight; resilience", tags: ["용기", "인내", "노력"] },
  { word: "사필귀정", hanja: "事必歸正", meaning: "모든 일은 반드시 바른 데로 돌아감. 결국 옳고 그름이 밝혀짐", english: "Justice will prevail in the end", tags: ["정의"] },
  { word: "고진감래", hanja: "苦盡甘來", meaning: "쓴 것이 다하면 단 것이 옴 → 고생 끝에 낙이 옴", english: "After hardship comes happiness", tags: ["희망", "인내"] },
  { word: "자업자득", hanja: "自業自得", meaning: "자신이 저지른 일의 결과를 자신이 받음. 뿌린 대로 거둠", english: "You reap what you sow", tags: ["인과"] },
  { word: "학수고대", hanja: "鶴首苦待", meaning: "학처럼 목을 길게 빼고 몹시 기다림", english: "Eagerly waiting with outstretched neck", tags: ["기다림"] },
  { word: "일취월장", hanja: "日就月將", meaning: "날로 나아가고 달로 발전함 → 꾸준히 성장함", english: "Making progress day by day and month by month", tags: ["성장", "노력"] },
  { word: "주마간산", hanja: "走馬看山", meaning: "말을 타고 달리면서 산을 봄 → 자세히 살피지 않고 대충 훑어봄", english: "A cursory glance; viewing while speeding past", tags: ["태도"] },
  { word: "수수방관", hanja: "袖手傍觀", meaning: "팔짱을 낀 채 곁에서 구경만 함 → 관여하지 않고 내버려 둠", english: "Standing by with folded arms; turning a blind eye", tags: ["태도"] },
  { word: "배은망덕", hanja: "背恩忘德", meaning: "받은 은혜를 저버리고 도리어 배반함", english: "Biting the hand that feeds you; ingratitude", tags: ["인성"] },
  { word: "구사일생", hanja: "九死一生", meaning: "아홉 번 죽을 고비에서 겨우 살아남 → 기적적으로 살아남", english: "A narrow escape from death", tags: ["위기", "용기"] },
  { word: "어불성설", hanja: "語不成說", meaning: "말이 사리에 맞지 않아 이치가 없음", english: "That doesn't make sense; illogical argument", tags: ["소통"] },
  { word: "역지사지", hanja: "易地思之", meaning: "처지를 바꾸어 생각해 봄 → 상대방의 입장에서 헤아림", english: "Put yourself in another's shoes", tags: ["공감", "이해"] },
  { word: "오비이락", hanja: "烏飛梨落", meaning: "까마귀 날자 배 떨어진다 → 공교롭게 두 일이 같은 때에 일어남", english: "Guilty by coincidence; two unrelated things happening simultaneously", tags: ["오해"] },
  { word: "좌불안석", hanja: "坐不安席", meaning: "앉아 있어도 자리가 편하지 않음 → 불안하여 안절부절못함", english: "Unable to sit still; feeling uneasy and restless", tags: ["불안"] },
  { word: "조삼모사", hanja: "朝三暮四", meaning: "아침에 세 개, 저녁에 네 개 → 간사한 꾀로 남을 속임. 결국 같은 것을 당장만 다른 것처럼 속임", english: "Short-term thinking; being fooled by superficial differences", tags: ["기만"] },
  { word: "인과응보", hanja: "因果應報", meaning: "원인에 따라 결과가 응함. 선한 일에는 선한 결과, 악한 일에는 악한 결과", english: "Karma; what goes around comes around", tags: ["인과", "정의"] },
  { word: "독불장군", hanja: "獨不將軍", meaning: "혼자서는 장군이 될 수 없다 → 독단적이고 남과 어울리지 못하는 사람", english: "No man is an island; can't succeed alone", tags: ["협력", "인간관계"] },
  { word: "점입가경", hanja: "漸入佳境", meaning: "점점 더 좋은 경지로 들어감. 또는 일이 점점 더 재미있어지거나 어이없어짐", english: "Getting more and more interesting (or outrageous)", tags: ["변화"] },
  { word: "온화지신", hanja: "溫和之信", meaning: "온화하고 믿음직함. 부드러운 덕성을 갖춤", english: "Gentle and trustworthy character", tags: ["인성"] },
  { word: "화룡점정", hanja: "畵龍點睛", meaning: "용을 그린 뒤 눈동자를 찍음 → 가장 중요한 마지막 마무리로 완성도를 높임", english: "The finishing touch that brings something to life", tags: ["완성", "지혜"] },
  { word: "우공이산", hanja: "愚公移山", meaning: "우공이 산을 옮김 → 우직하게 꾸준히 노력하면 목표를 이룸", english: "Persistent effort can move mountains", tags: ["노력", "인내"] },
  { word: "견리사의", hanja: "見利思義", meaning: "이익을 보면 의로움을 생각함. 작은 이익보다 올바름을 먼저 생각함", english: "Think of righteousness before profit", tags: ["인성", "덕"] },
  { word: "지피지기", hanja: "知彼知己", meaning: "적을 알고 나를 앎 → 백 번 싸워도 지지 않음", english: "Know your enemy and know yourself", tags: ["전략", "지혜"] },
  { word: "십시일반", hanja: "十匙一飯", meaning: "열 사람이 한 숟가락씩 보태면 한 사람 밥이 됨 → 여럿이 조금씩 도우면 큰 힘이 됨", english: "Many a little makes a muckle; collective effort", tags: ["협력", "나눔"] },
  { word: "무릉도원", hanja: "武陵桃源", meaning: "이상적이고 아름다운 별세계 → 꿈 같은 이상향", english: "Utopia; an idyllic paradise", tags: ["이상"] },
  { word: "명실상부", hanja: "名實相符", meaning: "이름과 실제가 서로 들어맞음", english: "Living up to one's name; worthy of the title", tags: ["신뢰"] },
];

export const SODAM_DATA: SodamEntry[] = [
  { sodam: "가는 말이 고와야 오는 말이 곱다", meaning: "남에게 잘 대해야 자신도 좋은 대우를 받는다", english: "Treat others as you wish to be treated", tags: ["인간관계", "배려"] },
  { sodam: "고생 끝에 낙이 온다", meaning: "힘든 일을 겪고 나면 즐거운 일이 따라온다", english: "No pain, no gain", tags: ["인내", "희망"] },
  { sodam: "공든 탑이 무너지랴", meaning: "정성껏 쌓은 것은 쉽게 무너지지 않는다", english: "Hard work pays off; what is built with care endures", tags: ["노력"] },
  { sodam: "낮말은 새가 듣고 밤말은 쥐가 듣는다", meaning: "말은 항상 조심해야 한다. 비밀은 없다", english: "Walls have ears; be careful what you say", tags: ["조심", "말"] },
  { sodam: "하늘이 무너져도 솟아날 구멍이 있다", meaning: "아무리 어려운 상황에서도 살아날 방도가 있다", english: "Every cloud has a silver lining", tags: ["희망"] },
  { sodam: "세 살 버릇 여든까지 간다", meaning: "어릴 때 몸에 밴 습관은 늙어서도 쉽게 고치지 못한다", english: "Old habits die hard", tags: ["습관", "교육"] },
  { sodam: "원숭이도 나무에서 떨어진다", meaning: "아무리 능숙한 사람도 실수할 수 있다", english: "Even Homer sometimes nods; nobody is perfect", tags: ["실수"] },
  { sodam: "호랑이도 제 말 하면 온다", meaning: "누군가의 이야기를 하면 마침 그 사람이 나타난다", english: "Talk of the devil and he shall appear", tags: ["우연"] },
  { sodam: "발 없는 말이 천 리 간다", meaning: "말은 아무리 먼 곳에도 금방 전해진다. 말 조심해라", english: "Words have wings; news travels fast", tags: ["말", "조심"] },
  { sodam: "배보다 배꼽이 크다", meaning: "기본보다 부수적인 것이 더 커지거나 중요해진다", english: "The tail wagging the dog", tags: ["균형"] },
  { sodam: "빈 수레가 요란하다", meaning: "아는 것이 없는 사람이 오히려 더 떠들어댄다", english: "Empty vessels make the most noise", tags: ["겸손"] },
  { sodam: "아 다르고 어 다르다", meaning: "같은 내용이라도 표현에 따라 전혀 다르게 들린다", english: "It's not what you say but how you say it", tags: ["말", "소통"] },
  { sodam: "될성부른 나무는 떡잎부터 알아본다", meaning: "장래가 기대되는 사람은 어릴 때부터 그 됨됨이가 보인다", english: "Great oaks from little acorns grow; talent shows early", tags: ["재능"] },
  { sodam: "지렁이도 밟으면 꿈틀한다", meaning: "아무리 약한 존재도 한계를 넘으면 반발한다", english: "Even a worm will turn; push anyone too far and they will react", tags: ["인내", "반발"] },
  { sodam: "꿩 먹고 알 먹는다", meaning: "한 가지 일로 두 가지 이득을 본다", english: "Kill two birds with one stone", tags: ["효율"] },
  { sodam: "소 잃고 외양간 고친다", meaning: "일이 이미 잘못된 후에야 뒤늦게 대책을 세운다", english: "Locking the stable door after the horse has bolted", tags: ["준비", "후회"] },
  { sodam: "티끌 모아 태산", meaning: "아주 작은 것도 모이면 큰 것이 된다", english: "Many a mickle makes a muckle; every little bit counts", tags: ["노력", "절약"] },
  { sodam: "굴러온 돌이 박힌 돌 뺀다", meaning: "나중에 온 사람이 먼저 있던 사람의 자리를 빼앗는다", english: "The newcomer takes over", tags: ["인간관계"] },
  { sodam: "말 한마디에 천 냥 빚도 갚는다", meaning: "말을 잘하면 어렵고 큰 문제도 해결할 수 있다", english: "A word fitly spoken is like gold", tags: ["말", "지혜"] },
  { sodam: "우물 안 개구리", meaning: "좁은 경험과 지식으로 세상 전체를 판단하는 사람", english: "A frog in a well; having a narrow worldview", tags: ["견문", "겸손"] },
  { sodam: "콩 심은 데 콩 나고 팥 심은 데 팥 난다", meaning: "원인에 따라 결과가 나타난다. 뿌린 대로 거둔다", english: "You reap what you sow", tags: ["인과"] },
  { sodam: "도둑이 제 발 저리다", meaning: "죄를 지은 사람이 탄로날까 봐 두려워 스스로 불안해한다", english: "A guilty conscience needs no accuser", tags: ["양심"] },
  { sodam: "등잔 밑이 어둡다", meaning: "가장 가까이에 있는 것을 오히려 모른다", english: "The darkest place is under the candlestick", tags: ["맹점", "주의"] },
  { sodam: "뛰는 놈 위에 나는 놈 있다", meaning: "잘 하는 사람 위에 더 잘 하는 사람이 있다. 교만하지 말아라", english: "There is always someone better than you; pride comes before a fall", tags: ["겸손"] },
  { sodam: "개천에서 용 난다", meaning: "변변치 않은 환경에서 뛰어난 인물이 난다", english: "A diamond in the rough; rising from humble beginnings", tags: ["성공", "희망"] },
  { sodam: "닭 잡아먹고 오리발 내민다", meaning: "잘못을 저지르고 엉뚱한 것으로 속이려 한다", english: "Cover up wrongdoing with a lame excuse", tags: ["정직", "기만"] },
  { sodam: "가랑비에 옷 젖는다", meaning: "사소한 것이라도 자꾸 쌓이면 큰 영향을 미친다", english: "Dripping water hollows out a stone", tags: ["지속성"] },
  { sodam: "모로 가도 서울만 가면 된다", meaning: "방법이 어떻든 목적만 이루면 된다", english: "The end justifies the means; any road will do if you don't know where you're going", tags: ["목표"] },
  { sodam: "사공이 많으면 배가 산으로 간다", meaning: "지휘하는 사람이 많으면 일이 엉뚱한 방향으로 흐른다", english: "Too many cooks spoil the broth", tags: ["리더십", "협력"] },
  { sodam: "시작이 반이다", meaning: "무슨 일이든 시작만 하면 절반은 한 것이나 마찬가지다", english: "Well begun is half done", tags: ["실행", "노력"] },
  { sodam: "열 번 찍어 안 넘어가는 나무 없다", meaning: "무슨 일이든 열심히 거듭 노력하면 이룰 수 있다", english: "Perseverance wins in the end", tags: ["노력", "인내"] },
  { sodam: "쥐구멍에도 볕 들 날 있다", meaning: "아무리 불행한 사람도 운이 트이는 때가 있다", english: "Every dog has its day", tags: ["희망"] },
  { sodam: "아니 땐 굴뚝에 연기 나랴", meaning: "원인 없는 결과는 없다. 소문에는 반드시 이유가 있다", english: "Where there's smoke there's fire", tags: ["인과"] },
  { sodam: "작은 고추가 더 맵다", meaning: "작고 약해 보이는 것이 오히려 더 강하거나 능력이 있다", english: "Big things come in small packages", tags: ["편견"] },
  { sodam: "자라 보고 놀란 가슴 솥뚜껑 보고 놀란다", meaning: "한 번 놀란 경험 때문에 비슷한 것만 봐도 무서워한다", english: "Once bitten, twice shy", tags: ["트라우마", "조심"] },
  { sodam: "바늘 도둑이 소 도둑 된다", meaning: "작은 잘못을 방치하면 결국 큰 잘못으로 커진다", english: "He that will steal a pin will steal a better thing", tags: ["도덕", "습관"] },
  { sodam: "하늘은 스스로 돕는 자를 돕는다", meaning: "자신이 노력하는 사람에게 하늘도 돕는다", english: "God helps those who help themselves", tags: ["노력", "자립"] },
  { sodam: "윗물이 맑아야 아랫물이 맑다", meaning: "윗사람이 모범을 보여야 아랫사람도 바르게 된다", english: "A fish rots from the head down; leadership sets the tone", tags: ["리더십", "모범"] },
  { sodam: "참을 인 자 셋이면 살인도 면한다", meaning: "인내하고 참으면 큰 화를 피할 수 있다", english: "Patience is a virtue; count to ten before acting", tags: ["인내", "절제"] },
  { sodam: "눈 가리고 아웅", meaning: "얕은 꾀로 남을 속이려 하지만 뻔히 드러남", english: "Pulling the wool over someone's eyes poorly", tags: ["기만", "속임"] },
  { sodam: "혹 떼러 갔다 혹 붙여 온다", meaning: "이익을 얻으려다가 오히려 손해를 보고 돌아온다", english: "Go for wool and come home shorn", tags: ["실패", "욕심"] },
  { sodam: "핑계 없는 무덤 없다", meaning: "어떤 잘못에도 변명은 항상 있다", english: "There is always an excuse", tags: ["책임"] },
  { sodam: "부뚜막의 소금도 집어넣어야 짜다", meaning: "아무리 좋은 조건이 갖춰져 있어도 실행해야 효과가 있다", english: "Knowledge without action is useless", tags: ["실행"] },
  { sodam: "세월이 약이다", meaning: "시간이 지나면 어떤 슬픔이나 고통도 차츰 나아진다", english: "Time heals all wounds", tags: ["치유", "인내"] },
  { sodam: "입이 열 개라도 할 말이 없다", meaning: "잘못이 너무 명백하여 아무리 변명해도 할 말이 없다", english: "No excuse can be made; caught red-handed", tags: ["책임"] },
  { sodam: "구르는 돌은 이끼가 안 낀다", meaning: "부지런히 활동하는 사람은 발전하고 기회를 잡는다", english: "A rolling stone gathers no moss", tags: ["노력", "활동"] },
  { sodam: "가는 날이 장날", meaning: "방문한 날이 마침 바쁜 날이거나, 공교롭게 딱 맞는 때", english: "Just my luck; arriving on the wrong (or right) day by coincidence", tags: ["우연"] },
  { sodam: "호미로 막을 것을 가래로 막는다", meaning: "작을 때 쉽게 처리할 수 있을 것을 내버려 두었다가 크게 애먹는다", english: "A stitch in time saves nine", tags: ["미리", "준비"] },
  { sodam: "까마귀 날자 배 떨어진다", meaning: "두 사건이 공교롭게 같은 때에 일어나 오해를 받다", english: "Guilty by coincidence; bad timing", tags: ["오해", "우연"] },
  { sodam: "열길 물속은 알아도 한 길 사람 속은 모른다", meaning: "물속 깊이는 알 수 있어도 사람 마음은 알기 어렵다", english: "You can know the depth of the sea but not the heart of a person", tags: ["인간관계", "신뢰"] },
];
